<?php
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME']) && realpath((string) $_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    header('X-Robots-Tag: noindex, nofollow, noarchive', true);
    http_response_code(404);
    exit;
}

$data = require __DIR__ . '/germany-war-stress-test.php';
$data['meta'] = array_replace($data['meta'], [
    'warning'=>'This scenario studies an extreme chain of events. It does not say what will happen. It asks what could happen if several safeguards fail at the same time.',
    'inspiration'=>'Carlo Masala’s book “Wenn Russland gewinnt” inspired the main question. RealityCheck developed this fictional stress test independently.',
    'noProbability'=>'The dossier gives no probability. The chain is not certain and cannot be measured reliably.',
]);
$data['legalGeography'] = [
    'natoMembers'=>'Estonia, Latvia, Lithuania, Finland, Poland, Romania and Bulgaria are NATO members. An armed attack on one of them concerns collective defence under Article 5.',
    'nonMembers'=>'Georgia and Moldova are not NATO members. Article 5 does not apply to support for them.',
    'article5'=>'Article 5 requires collective defence. It does not force every ally to give exactly the same response. Each member takes the action it considers necessary. This can include military force.',
    'openAttack'=>'A Russian missile or drone strike on Germany would be more than hybrid pressure. It would be an open military escalation between Russia and NATO.',
    'nuclear'=>'A direct conflict between Russia and NATO would create a real risk of unintended or nuclear escalation. No responsible exact probability can be given.',
];
$data['strategicDoctrine'] = [
    'headline'=>'Germany must be able to defend its people and its democratic order.',
    'text'=>'This includes credible military force when defence is necessary, lawful and proportionate. Parliament and the Alliance must control it. Capability is not a promise to fight. It should remove an attacker’s hope of quick success and give diplomacy more weight.',
    'trade'=>'“Change through trade” was not enough as a security policy. Trade remains useful. However, economic dependence must not become a weapon against democratic decisions.',
    'energy'=>'Renewable energy, grids, storage, efficiency and European connections are also security infrastructure. They reduce fossil import risk, soften supply and price shocks, protect homes and firms and support climate protection.',
];
$objections = [
 ['title'=>'“Better red than dead.”','core'=>'Avoiding nuclear war and refusing to kill are serious moral positions. A democracy must protect conscientious objection. It must not call every objector disloyal.','reply'=>'The problem does not end with refusing defence today. If outside force destroyed German democracy, a later system might no longer protect protest or conscientious objection. It could force people to support further expansion. Present-day Russia shows this difference: refusal and desertion can lead to long prison terms, and pressure to sign military contracts has been reported. This is a warning about lost rights, not a prediction of one exact future.','evidence'=>'The EU asylum agency documents compulsory service in Russia, reported pressure to sign contracts and prison terms of seven to fifteen years for desertion during mobilisation or war.','uncertainty'=>'Nuclear escalation would be catastrophic. We cannot know the exact form of Russian control in a fictional defeat. Defence, diplomacy, arms control and crisis communication must therefore work together.'],
 ['title'=>'“Soldiers are murderers.”','core'=>'Tucholsky’s sentence contains an important warning. Armed forces prepare people for organised violence, and a uniform does not remove personal responsibility. Soldiers can kill illegally and military organisations can commit crimes.','reply'=>'However, “murderer” is not a fair description of every soldier. In a parliamentary democracy, soldiers do not decide alone whether the country goes to war. They carry out a legally controlled task and face the most direct physical and moral risks. They may have to kill and may themselves be killed or injured. The democratic ideal is not hero worship or group condemnation. It is the thinking “citizen in uniform”, bound by law and conscience and required to refuse criminal orders.','evidence'=>'The sentence comes from Tucholsky’s 1931 criticism of war. In 1995, the Constitutional Court overturned convictions because free expression had not been considered properly. It did not say that soldiers and murderers are the same. Bundeswehr doctrine also rejects blind obedience.','uncertainty'=>'Soldiers can be victims, protectors, offenders or more than one of these during a conflict. Democratic control, international law, training, investigation and personal responsibility must limit military violence.'],
 ['title'=>'“If war starts, I will just leave.”','core'=>'Flight can be a lawful and understandable way to protect yourself, children or relatives. Survival is not cowardice. People who qualify for protection keep their rights.','reply'=>'But “leave” is not a complete emergency plan. A person must be allowed to exit, find a working route, enter another country, receive a status longer than a short visit and find housing, income, health care and school. Ukraine shows that wartime law can limit departure. Canada shows that an eTA does not guarantee entry and that special programmes can change or close. In a NATO-wide war, no one can safely assume that a distant country will offer unlimited entry and permanent residence at the right moment.','evidence'=>'Ukraine restricted departure for many military-age men after mobilisation. Canada ended new applications to its CUAET programme in 2023 and later limited other measures. EU research also found financial hardship, unsafe housing, exploitation and violence among displaced Ukrainian women. The United States deported some Ukrainian men in 2026 under immigration law, but not simply because all men of draft age were being expelled.','uncertainty'=>'No one can predict the border policy of a future NATO war. Other countries might create new protection routes. Refugee protection must not depend on military service. The responsible point is smaller: flight may be necessary, but it is not guaranteed, easy or permanent. Documents, family meeting points and official evacuation information are useful preparation.'],
 ['title'=>'“Russia has no interest in Germany.”','core'=>'A full occupation of Germany is not the simplest path to Russian goals.','reply'=>'In this stress test, Germany matters as a NATO decision-maker and logistics centre. Russia could try to disrupt these roles without seeking permanent occupation.','evidence'=>'German and NATO planning describe support for Allied reinforcement as a strategic task.','uncertainty'=>'Intentions can change and cannot be known with certainty.'],
 ['title'=>'“NATO threatens Russia.”','core'=>'Russian leaders can view NATO enlargement and Allied forces as a threat.','reply'=>'This perception matters, but it does not remove the right of neighbouring states to choose their own policy. It also does not justify aggression. NATO describes its role as defensive.','evidence'=>'The North Atlantic Treaty and current NATO plans focus on collective defence, not conquest.','uncertainty'=>'A security dilemma can remain even when a state says its actions are defensive.'],
 ['title'=>'“More weapons automatically mean more war.”','core'=>'Weapons can increase arms races and make escalation more destructive.','reply'=>'The effect depends on their purpose and position. Defensive forces, transparency and Alliance control can reduce the expected benefit of aggression.','evidence'=>'Research on the security dilemma separates offensive advantage from a clearly defensive position.','uncertainty'=>'Different actors may still read the same force in different ways.'],
 ['title'=>'“Defence is pointless in a nuclear war.”','core'=>'A large nuclear war would be catastrophic. Civil protection cannot make it controllable.','reply'=>'Defence also tries to stop conventional force and keep escalation below the nuclear level. Preparation can still save lives during outages and conventional attacks.','evidence'=>'NATO combines deterrence with resilience. BBK advice covers many crises and promises no complete safety.','uncertainty'=>'Nuclear escalation remains an extreme risk.'],
 ['title'=>'“Diplomacy is the only solution.”','core'=>'Wars end through political decisions. Communication and negotiated limits are essential.','reply'=>'Diplomacy works within incentives. If one side expects greater success from force, talks alone may not stop an attack.','evidence'=>'Arms control worked best with verification, deterrence and continued communication.','uncertainty'=>'The right balance depends on the time and the other side.'],
 ['title'=>'“A professional army is enough.”','core'=>'Modern armed forces need skilled, long-serving professionals.','reply'=>'Long defence also needs a reserve, logistics, medicine, cyber skills, infrastructure and support for Allied forces. Professionals remain the core, but trained extra personnel may be necessary.','evidence'=>'German planning gives roles to active forces, the reserve, territorial defence and civilian organisations.','uncertainty'=>'The real need depends on strategy, technology and Alliance burden sharing.'],
 ['title'=>'“Conscription is always undemocratic.”','core'=>'Compulsory service is a serious limit on freedom and can be unfair.','reply'=>'Democratic legitimacy needs law, a proven need, equal treatment, conscientious objection, oversight, fair pay and real training capacity.','evidence'=>'Germany’s Basic Law protects conscientious objection and contains rules for compulsory service.','uncertainty'=>'A legal model can still be unfair or poorly designed.'],
 ['title'=>'“Germany could simply be neutral.”','core'=>'Neutrality can reduce Alliance involvement in some situations.','reply'=>'Germany is deeply connected to the EU and NATO. Leaving alone would not remove risks to infrastructure, cyber systems or trade. It would require major political, legal and military choices.','evidence'=>'Germany has binding Alliance commitments and is central to European logistics and markets.','uncertainty'=>'Neutrality works only if other states accept it and the neutral state can defend itself.'],
];
foreach ($data['objections'] as $index => &$objection) $objection = array_replace($objection, $objections[$index]);
unset($objection);
$data['people']['serviceDebate'] = array_replace($data['people']['serviceDebate'], [
    'intro'=>'Service should mean responsibility for the democratic community and the people who live in it. It must not mean blind loyalty to a government or to an ethnic idea of the nation. Military readiness, civil resilience and social learning are different goals. One compulsory programme will not automatically reach all three.',
    'learning'=>'A good service programme can create contact between social groups and teach responsibility, teamwork, conflict skills and independence. German studies found such development in voluntary services and the former civilian service. They do not prove that compulsion caused it. The quality of the placement, supervision and useful work also matter.',
    'conclusion'=>'My assessment: first expand attractive voluntary service and build the instructors, placements and reserve structures that every model needs. If a proven military gap remains, a needs-based and gender-equal defence service with a real civilian alternative is easier to justify than a universal year sold mainly as moral education.',
]);
return $data;
