<?php
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME']) && realpath((string) $_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    header('X-Robots-Tag: noindex, nofollow, noarchive', true);
    http_response_code(404);
    exit;
}

$data = require __DIR__ . '/germany-war-stress-test.php';
$data['meta'] = array_replace($data['meta'], [
    'title'=>'Sonderszenario: Deutschland im Krieg',
    'subtitle'=>'Ein sicherheitspolitischer Stresstest – keine Prognose',
    'warning'=>'Dieses Szenario untersucht eine extreme Eskalationskette. Es beschreibt nicht, was geschehen wird. Es zeigt, was geschehen könnte, wenn mehrere Schutzmechanismen gleichzeitig versagen.',
    'inspiration'=>'Die Grundfrage ist durch Carlo Masalas Buch „Wenn Russland gewinnt“ angeregt. Die hier gezeigte Kette wurde jedoch unabhängig entwickelt und klar als fiktiver Stresstest gekennzeichnet.',
    'noProbability'=>'Es wird keine Wahrscheinlichkeit genannt. Die Kette ist weder unvermeidlich noch zuverlässig berechenbar.',
]);
$evidenceText = [
    'observed'=>['label'=>'Beobachtete Tatsache','description'=>'Ein bereits dokumentiertes Ereignis oder eine beobachtete Fähigkeit.'],
    'official'=>['label'=>'Amtliche Einschätzung','description'=>'Veröffentlichte Einschätzung oder Politik einer staatlichen Institution.'],
    'research'=>['label'=>'Forschungsinterpretation','description'=>'Erklärung eines Zusammenhangs aus Wissenschaft oder Politikforschung.'],
    'history'=>['label'=>'Historischer Vergleich','description'=>'Ein Vergleich erklärt mögliche Mechanismen, beweist aber keine Wiederholung.'],
    'plausible'=>['label'=>'Plausible Szenarioannahme','description'=>'Eine mögliche Entwicklung aus bekannten Mechanismen, keine Vorhersage.'],
    'extreme'=>['label'=>'Extreme Stressannahme','description'=>'Eine absichtlich harte fiktive Annahme, mit der Widerstandskraft geprüft wird.'],
    'unknown'=>['label'=>'Nicht seriös berechenbar','description'=>'Richtung oder Folge ist denkbar. Zeitpunkt und Größe lassen sich nicht verantwortungsvoll schätzen.'],
];
foreach ($data['evidenceTypes'] as $id => &$type) $type = array_replace($type, $evidenceText[$id]);
unset($type);
$startText = [
    'Russland führt einen Angriffskrieg gegen die Ukraine. Neben militärischer Gewalt nutzt es Cyberangriffe, Sabotage, Informationsmanipulation und politischen Druck.',
    'Die NATO bezeichnet Russland als wichtigste direkte Bedrohung für die Sicherheit der Bündnisstaaten und hat ihre Ostflanke verstärkt.',
    'Deutschland plant als Aufnahmeland und logistisches Zentrum für Bewegungen der Alliierten und für die Landesverteidigung. Daraus entsteht Verantwortung, aber keine Gewissheit eines Angriffs.',
    'Die Simulation nimmt an: Russland setzt sich in der Ukraine durch, Europa entspannt sich zu früh, ein begrenzter Angriff testet die NATO, Abschreckung versagt und Deutschland wird offen angegriffen.',
];
foreach ($data['startingPoints'] as $i => &$point) $point['text'] = $startText[$i];
unset($point);
$data['legalGeography'] = [
    'natoMembers'=>'Estland, Lettland, Litauen, Finnland, Polen, Rumänien und Bulgarien sind NATO-Mitglieder. Ein bewaffneter Angriff auf einen dieser Staaten betrifft die gemeinsame Verteidigung nach Artikel 5.',
    'nonMembers'=>'Georgien und Moldau sind keine NATO-Mitglieder. Für ihre Unterstützung gilt Artikel 5 nicht.',
    'article5'=>'Artikel 5 verpflichtet zur gemeinsamen Verteidigung. Er führt aber nicht automatisch zu derselben Reaktion jedes Verbündeten. Jeder Mitgliedstaat ergreift die Maßnahmen, die er für nötig hält. Dazu kann auch militärische Gewalt gehören.',
    'openAttack'=>'Ein russischer Raketen- oder Drohnenangriff auf Deutschland wäre nicht nur hybrider Druck. Er wäre eine offene militärische Eskalation zwischen Russland und der NATO.',
    'nuclear'=>'Jeder direkte Konflikt zwischen Russland und der NATO hätte das Risiko einer unbeabsichtigten oder nuklearen Eskalation. Dieses Risiko ist real, lässt sich hier aber nicht seriös als genaue Wahrscheinlichkeit angeben.',
];
$data['strategicDoctrine'] = [
    'headline'=>'Deutschland muss seine Bevölkerung und seine demokratische Ordnung verteidigen können.',
    'text'=>'Dazu gehört eine glaubwürdige militärische Fähigkeit, wenn Verteidigung nötig, rechtmäßig und verhältnismäßig ist. Sie bleibt unter parlamentarischer und gemeinsamer Kontrolle. Fähigkeit ist kein Versprechen zu kämpfen. Sie soll einem Angreifer die Hoffnung auf einen schnellen Erfolg nehmen und Diplomatie mehr Gewicht geben.',
    'trade'=>'„Wandel durch Handel“ hat als ausreichende Sicherheitsstrategie versagt. Handel bleibt nützlich. Wirtschaftliche Abhängigkeit darf aber nicht als Waffe gegen demokratische Entscheidungen eingesetzt werden können.',
    'energy'=>'Erneuerbare Energie, Netze, Speicher, Effizienz und europäische Verbindungen sind deshalb auch Sicherheitsinfrastruktur. Sie verringern die Abhängigkeit von fossilen Importen, dämpfen Liefer- und Preisschocks, schützen Unternehmen und Haushalte und helfen Klima und Umwelt.',
];
$phaseText = [
  1=>['title'=>'Russland setzt sich in der Ukraine durch','event'=>'Russland behält große besetzte Gebiete. Die Ukraine ist militärisch und wirtschaftlich geschwächt. Teile Europas deuten einen Waffenstillstand als dauerhafte Entspannung und verschieben Verteidigungsprogramme.','aim'=>'Gebiets- und Machtgewinne sichern, die ukrainische Selbstständigkeit schwächen und prüfen, ob die Aufmerksamkeit des Westens nachlässt.','response'=>'Die Widerstandskraft der Ukraine unterstützen, Sanktionen und glaubwürdige Verteidigungsplanung erhalten und einen Waffenstillstand nicht mit dauerhaftem Frieden verwechseln.','citizens'=>'Haushaltskonflikte werden härter. Geflüchtete bleiben möglicherweise lange vertrieben. Die öffentliche Debatte schwankt zwischen Erleichterung, Müdigkeit und Sorge.','risk'=>'Der Eindruck, dass Zwang Erfolg bringt, kann spätere Entscheidungen verändern.','prevention'=>'Ukraine dauerhaft unterstützen, eine Siegeserzählung verhindern, europäische Beschaffung und Bereitschaft im Zeitplan halten und diplomatische Kanäle offenlassen.'],
  2=>['title'=>'Wiederaufbau und hybride Offensive','event'=>'Das Szenario nimmt an, dass Russland Streitkräfte, Munition und Produktion wieder aufbaut. Gleichzeitig nehmen Cyberangriffe, Sabotage, GPS-Störungen, Aufklärung, Desinformation und politische Einflussnahme zu.','aim'=>'Europas Bereitschaft senken, Schwachstellen erfassen und Streit über Verteidigungsausgaben, Dienstpflicht und Unterstützung für östliche Partner vertiefen.','response'=>'Vorfälle schneller zuordnen, Informationen teilen, Infrastruktur schützen, Krisenentscheidungen üben und gemeinsam reagieren, statt jeden Vorfall einzeln zu behandeln.','citizens'=>'Mehr Ausfälle und Falschmeldungen sind möglich. Vertrauen in Institutionen und geprüfte Informationen wird selbst zu einem Sicherheitsfaktor.','risk'=>'Mehrdeutige Angriffe können Lähmung oder eine unkontrollierte Gegenreaktion auslösen.','prevention'=>'Cyberabwehr, Ersatzsysteme, klare öffentliche Kommunikation, Schutz der Infrastruktur und abgestufte gemeinsame Antworten.'],
  3=>['title'=>'Druck auf Staaten außerhalb der NATO','event'=>'Moldau und Georgien werden durch politischen, wirtschaftlichen, informativen und militärischen Druck destabilisiert. Ungelöste Konflikte und vorhandene russische Truppen dienen als Hebel.','aim'=>'Freie Entscheidungen einschränken, Abhängigkeit schaffen und zeigen, dass westliche Partnerschaft keinen Schutz bietet.','response'=>'EU-Hilfe, Sanktionen, zivile Missionen, wirtschaftliche Widerstandskraft und Unterstützung demokratischer Institutionen. Artikel 5 gilt nicht.','citizens'=>'Wirtschaftliche Unsicherheit, Vertreibung und Polarisierung steigen in den betroffenen Staaten. Europa steht erneut unter humanitärem und politischem Druck.','risk'=>'Lokale Vorfälle können Grenzen überschreiten oder als Vorbereitung eines größeren Angriffs missverstanden werden.','prevention'=>'Institutionen, Beobachtung, Vermittlung und Krisenkommunikation stärken und die rechtlichen Grenzen der Bündnisse klar benennen.'],
  4=>['title'=>'Ein begrenzter Test der NATO','event'=>'Fiktive Stressannahme: Russland besetzt ein kleines Gebiet eines baltischen NATO-Staates. Es bezeichnet den Angriff als lokale Schutz-, Grenz- oder Anti-Terror-Maßnahme und droht mit weiterer Eskalation.','aim'=>'Prüfen, ob die NATO einen kleinen Gebietsverlust hinnimmt, um einen größeren Krieg zu vermeiden. Ziel ist zunächst nicht die Eroberung Europas.','response'=>'Sofortige Beratungen nach Artikel 4, gemeinsame Bewertung und glaubwürdige Abwehr eines schnellen vollendeten Zustands. Gleichzeitig bleiben Kanäle zur Begrenzung der Eskalation offen.','citizens'=>'Angst vor einem größeren Krieg, Mobilisierung, Verkehrsstörungen und Desinformation verbreiten sich weit über das angegriffene Gebiet hinaus.','risk'=>'Zögern kann den Angriff belohnen. Hastige oder missverstandene Schritte können den Konflikt ausweiten.','prevention'=>'Vorwärtsverteidigung, geübte politische Entscheidungen, klare rote Linien, belastbare Kommunikation und schnelle Verstärkung.'],
  5=>['title'=>'Abschreckung versagt','event'=>'Einige Verbündete zögern. Angst vor nuklearer Eskalation und abgestimmte Desinformation verzögern Entscheidungen. Russland deutet die Uneinigkeit als geringe Bereitschaft, Bündnisgebiet zu verteidigen.','aim'=>'Politische Unklarheit in einen militärischen Vorteil verwandeln und Zugeständnisse erzwingen, ohne gegen das gesamte Bündnis kämpfen zu müssen.','response'=>'Beratung beschleunigen, Geschlossenheit zeigen, Zivilbevölkerung schützen, die Ostflanke verstärken und Festigkeit mit Krisenkommunikation verbinden.','citizens'=>'Märkte fallen, Lieferketten werden langsamer, Reservisten können einberufen werden und die demokratische Debatte gerät unter starken Druck.','risk'=>'Fehlwahrnehmungen auf beiden Seiten werden so gefährlich wie geplante Eskalation.','prevention'=>'Vorab vereinbarte Verfahren, eine klar defensive Haltung, Rüstungskontrollkontakte und politischer Zusammenhalt.'],
  6=>['title'=>'Deutschland wird Kriegsschauplatz','event'=>'Fiktive offene Kriegsannahme: Als NATO-Zentrum erlebt Deutschland Cyberangriffe, Sabotage, Störungen von Kommunikation und GPS sowie Drohnen-, Raketen- oder Marschflugkörperangriffe auf allgemein beschriebene militärische und logistische Funktionen. Es werden keine realen Ziele genannt.','aim'=>'Verstärkung, Führung, Verteidigungsproduktion und den Willen der Bevölkerung stören. Deutschland soll politisch von der Ostflanke getrennt werden.','response'=>'Luft- und Raketenabwehr, Cyberabwehr, Unterstützung der Alliierten, Schutz der Infrastruktur, handlungsfähige Regierung und gemeinsame Verteidigung. Das nukleare Risiko muss ausdrücklich begrenzt werden.','citizens'=>'Strom, Mobilfunk, Zahlungen und Verkehr können zeitweise ausfallen. Falsche Warnungen und Deepfakes erschweren Entscheidungen.','risk'=>'Ein Angriff auf Deutschland ist ein offener Krieg zwischen Russland und NATO. Er birgt ein schwer kontrollierbares konventionelles und nukleares Eskalationsrisiko.','prevention'=>'Glaubwürdige Verteidigung, verteilte Ersatzsysteme, ausgebildete Reserve, Zivilschutz, geschützte Krisenkanäle und Rüstungskontrolle.'],
  7=>['title'=>'Alltag im Konflikt','event'=>'Die Simulation untersucht Ausfälle bei Strom, Kommunikation, Verkehr, Versorgung, Schule, Verwaltung und Wirtschaft. Krankenhäuser geraten unter Druck. Vertreibung, Einberufung und stärkerer Schutz der Infrastruktur verändern den Alltag.','aim'=>'Der Angreifer will militärische Abläufe stören und die Gesellschaft erschöpfen. Auch das zivile Leben kann bewusst unter Druck gesetzt werden, selbst wenn Zivilisten nicht als Ziel bezeichnet werden.','response'=>'Behörden priorisieren Warnung, Rettungsdienste, kritische Versorgung, öffentliche Ordnung, geprüfte Informationen und Hilfe für besonders gefährdete Menschen.','citizens'=>'Preise steigen. Arbeit und Betreuung fallen aus. Psychischer Druck wächst. Militärische, wirtschaftliche und soziale Ziele geraten in Konflikt.','risk'=>'Gerüchte, Panikkäufe und ungleich verteilte Lasten können den Schaden über den eigentlichen Angriff hinaus vergrößern.','prevention'=>'Haushaltsvorsorge nach BBK, verlässliche lokale Netzwerke, Notfallpläne, psychologische Hilfe und transparente Kommunikation.'],
];
foreach ($data['phases'] as &$phase) $phase = array_replace($phase, $phaseText[$phase['id']]);
unset($phase);
$data['hours72'] = [
 ['time'=>'0–6 Stunden','title'=>'Warnung und Orientierung','items'=>['Offizielle Warnungen wie NINA, Radio und kommunale Kanäle nutzen.','Screenshots, Sprachnachrichten und dramatische Videos erst nach Bestätigung glauben.','Anweisungen der Behörden folgen und nicht losfahren, nur um zu sehen, was passiert.'],'authority'=>'Behörden bewerten den Vorfall, warnen auf gesicherter Grundlage und schützen die Notfallkommunikation.'],
 ['time'=>'6–24 Stunden','title'=>'Energie, Kommunikation und Verkehr','items'=>['Geräte und Powerbanks laden, solange Strom verfügbar ist. Batterieradio sparsam nutzen.','Straßen und Netze für Notfälle freihalten. Mit Einschränkungen bei Bahn und Nahverkehr rechnen.','Nahe Angehörige mit kurzen Nachrichten und einem vereinbarten Meldeplan kontaktieren.'],'authority'=>'Vorrang haben Rettungsdienste, Krankenhäuser, Wasser, Kommunikation und Verkehrssteuerung.'],
 ['time'=>'24–48 Stunden','title'=>'Versorgung, Arbeit, Schule und Gesundheit','items'=>['Bereits empfohlene Vorräte und Medikamente nutzen. Keine Panikkäufe.','Amtliche Informationen zu Schule, Arbeit, Betreuung und medizinischer Hilfe prüfen.','Hilfsbedürftige Nachbarn unterstützen, ohne sich selbst zu gefährden.'],'authority'=>'Kommunen organisieren bei Bedarf Notversorgung, Schutzräume oder Anlaufstellen.'],
 ['time'=>'48–72 Stunden','title'=>'Stabilisierung und geprüfte Informationen','items'=>['Batterien, Wasser und Lebensmittel sinnvoll einteilen. Dokumente und wichtige Medikamente griffbereit halten.','Dringende Notfälle über amtliche Wege melden und Gerüchte nicht weiterleiten.','Damit rechnen, dass Pläne sich mit neuen Erkenntnissen ändern.'],'authority'=>'Krisenstäbe aktualisieren Prioritäten, stellen Dienste wieder her und koordinieren regionale oder alliierte Hilfe.'],
];
$data['preparedness'] = ['title'=>'Persönliche Vorsorge – BBK-Empfehlung, kein Survivalismus','text'=>'Das BBK empfiehlt, sich möglichst zehn Tage selbst versorgen zu können. Schon drei Tage sind ein sinnvoller Anfang. Je nach eigener Lage gehören dazu Wasser, geeignete Lebensmittel, wichtige Medikamente, Erste Hilfe, Hygieneartikel, Batterieradio, Licht, geladene Powerbanks, wichtige Dokumente und etwas Bargeld. Waffen oder private Selbstjustiz werden hier nicht empfohlen.','source'=>'bbk'];
$householdText = [
 'single'=>['label'=>'Alleinlebende erwerbstätige Person','immediate'=>'Kommunikation und Arbeitsweg können ausfallen. Alle Entscheidungen und festen Haushaltskosten liegen bei einer Person.','economic'=>'Ein vorübergehender Arbeits- oder Zahlungsausfall wirkt schnell.','supply'=>'Keine zweite erwachsene Person kann einkaufen oder bei Krankheit pflegen.','work'=>'Arbeit von zu Hause kann ausfallen. Anwesenheit hängt von amtlichen Regeln und Verkehr ab.','support'=>'Notfallinformation, Einkommensschutz und kommunale Anlaufstellen.','needs'=>'Meldepartner, Medikamente, erreichbare Vorräte und Ersatzplan für Kommunikation.'],
 'family'=>['label'=>'Familie mit zwei Kindern','immediate'=>'Schul- und Betreuungsschließungen treffen auf Arbeit, Pflegeaufgaben und möglicherweise getrennte Familienmitglieder.','economic'=>'Kosten für Essen, Mobilität und Energie steigen, während Arbeitszeit sinken kann.','supply'=>'Kindgerechte Nahrung, Medikamente, Sicherheit und verständliche Informationen sind wichtig.','work'=>'Eltern können in wichtigen Berufen arbeiten oder gleichzeitig Betreuung leisten müssen.','support'=>'Information durch Schulen und Kommunen, Betreuung für kritische Berufe sowie Familien- und Wohnhilfen.','needs'=>'Altersgerechte Erklärung, Plan für das Wiederfinden und an Kinder angepasste Vorräte.'],
 'retired'=>['label'=>'Haushalt im Ruhestand','immediate'=>'Gesundheit, eingeschränkte Mobilität und wenig digitale Erfahrung können Warnungen und Ausfälle schwerer machen.','economic'=>'Feste Einkommen sind durch Preissprünge und Ausfälle von Diensten belastet.','supply'=>'Medikamente, Heizung oder Kühlung und barrierearme Informationen sind zentral.','work'=>'Keine direkte Arbeitswirkung. Pflege und Familienhilfe können aber ausfallen.','support'=>'Gesundheits- und Pflegedienste, barrierearme Warnung, Nachbarschaft und Kommune.','needs'=>'Medikamentenliste, analoges Radio, Notfallkontakte und Hilfe bei schweren Vorräten.'],
 'low'=>['label'=>'Haushalt mit geringem Einkommen','immediate'=>'Wenig Lagerraum und keine Rücklage machen schon kurze Störungen ernst.','economic'=>'Preissteigerungen und unterbrochene Zahlungen bedrohen sofort das Nötigste.','supply'=>'Ein Vorrat für zehn Tage kann ohne öffentliche Hilfe unbezahlbar sein.','work'=>'Unsichere Beschäftigung bietet oft weniger Flexibilität und Einkommensschutz.','support'=>'Gezielte Geld- und Sachhilfe, Notunterkunft, geschützte Versorgung und Schuldnerberatung.','needs'=>'Vorsorgepolitik muss sozial realistisch sein. Widerstandskraft darf nicht nur von Kaufkraft abhängen.'],
 'critical'=>['label'=>'Haushalt einer Arbeitskraft in kritischer Infrastruktur','immediate'=>'Lange Schichten und Anfahrtspflichten treffen auf Sorge um die Familie und gestörte Dienste.','economic'=>'Die Arbeit läuft weiter. Betreuungs- und Verkehrskosten steigen aber.','supply'=>'Der Haushalt braucht bei langer Abwesenheit einen verlässlichen Betreuungs- und Kommunikationsplan.','work'=>'Anwesenheit kann für Gesundheit, Energie, Wasser, Kommunikation oder Logistik nötig sein.','support'=>'Vorrangige Betreuung, geschützter Transport, Ruhezeiten, psychologische Hilfe und klare Arbeitgeberpläne.','needs'=>'Klare Rolle, Training und Schutz vor Erschöpfung.'],
];
foreach ($data['households'] as &$household) $household = array_replace($household, $householdText[$household['id']]);
unset($household);

$data['debate'] = [
    'title'=>'Macht Aufrüstung Krieg wahrscheinlicher?',
    'theses'=>[
        ['title'=>'A – Militärischer Aufbau kann ein Sicherheitsdilemma schaffen','argument'=>'Staaten können defensive Maßnahmen als Angriffsdrohung verstehen. Angriffsorientierte Fähigkeiten, Anreize zum Erstschlag und kurze Entscheidungszeiten können Wettrüsten und Eskalation fördern.','evidence'=>'Europa vor 1914 warnt vor Mobilisierungsdruck und Fehlwahrnehmung. Es beweist nicht, dass jede Aufrüstung Krieg verursacht.','uncertainty'=>'Absichten, Aufstellung der Streitkräfte, Transparenz und politischer Zusammenhang sind wichtig. Fähigkeit allein bestimmt das Ergebnis nicht.','source'=>'jervis'],
        ['title'=>'B – Zu schwache Verteidigung kann einen Angriff erleichtern','argument'=>'Ein Angreifer kann handeln, wenn er schnellen Erfolg, geringe Kosten und eine schwache Antwort erwartet. Glaubwürdige Abwehr senkt den erwarteten Gewinn.','evidence'=>'Beschwichtigung und späte Aufrüstung verhinderten in den 1930er-Jahren keine weitere deutsche Aggression. Russland griff 2022 die Ukraine außerhalb der NATO an. Die verstärkte NATO-Ostflanke wurde bisher nicht offen angegriffen.','uncertainty'=>'Diese Fälle sind kein mathematischer Beweis. Abschreckung kann versagen und militärische Stärke kann missbraucht werden.','source'=>'nato-deterrence'],
    ],
    'conclusion'=>'Nicht jede Aufrüstung schafft Sicherheit. Eine glaubwürdige, defensive und im Bündnis kontrollierte Fähigkeit kann die Erfolgschance eines Angriffs senken. Sie sollte mit Diplomatie, Rüstungskontrolle, Krisenkommunikation und politischer Berechenbarkeit verbunden sein.',
];
$objectionText = [
 ['title'=>'„Lieber rot als tot.“','core'=>'Nuklearkrieg zu vermeiden und das Töten abzulehnen sind moralisch ernste Positionen. Eine Demokratie muss Kriegsdienstverweigerung schützen und darf sie nicht als Verrat behandeln.','reply'=>'Das Dilemma endet nicht mit der heutigen Weigerung zur Verteidigung. Wenn Zwang die demokratische Selbstbestimmung Deutschlands zerstört, ist nicht sicher, dass eine spätere Ordnung Protest oder Gewissensfreiheit schützt. Sie könnte Menschen stattdessen zum Dienst für weitere Expansion zwingen. Das heutige russische System zeigt diese Ungleichheit: Verweigerung und Desertion können lange Haftstrafen bringen. Über Druck zum Abschluss militärischer Verträge wurde berichtet. Das ist eine Warnung vor verlorenen Rechten, keine genaue Prognose für eine mögliche Niederlage.','evidence'=>'Die EU-Asylagentur dokumentiert russische Dienstpflicht, berichteten Druck zum Vertragsabschluss und Strafen von sieben bis fünfzehn Jahren für Desertion während Mobilisierung oder Krieg.','uncertainty'=>'Nukleare Eskalation bleibt katastrophal. Die politische Form eines hypothetischen russischen Einflusses auf Deutschland ist unbekannt. Verteidigung, Diplomatie, Rüstungskontrolle und Eskalationskontrolle müssen gemeinsam verfolgt werden.'],
 ['title'=>'„Soldaten sind Mörder.“','core'=>'Tucholskys Provokation enthält eine wichtige moralische Warnung: Militär bereitet Menschen auf organisierte Gewalt vor. Eine Uniform hebt persönliche Verantwortung nicht auf. Soldaten können rechtswidrig töten und Streitkräfte können Verbrechen begehen.','reply'=>'„Mörder“ ist trotzdem keine ehrliche pauschale Beschreibung jedes Soldaten. In einer parlamentarischen Demokratie entscheiden Soldaten nicht allein über Krieg. Sie erfüllen einen rechtlich kontrollierten Auftrag und tragen dabei die direktesten körperlichen und moralischen Risiken. Sie trainieren für Krieg, können töten müssen und selbst getötet oder verletzt werden. Das demokratische Ideal ist weder Heldenverehrung noch pauschale Verurteilung. Es ist der denkende „Staatsbürger in Uniform“, der an Recht und Gewissen gebunden ist und verbrecherische Befehle ablehnen muss.','evidence'=>'Der Satz stammt aus Tucholskys Kritik von 1931. Das Bundesverfassungsgericht hob 1995 Verurteilungen wegen unzureichender Beachtung der Meinungsfreiheit auf. Es erklärte Soldaten und Mörder aber nicht für gleichbedeutend. Die Bundeswehr beschreibt selbst Lebensgefahr und die Möglichkeit des Tötens und lehnt blinden Gehorsam ab.','uncertainty'=>'Soldaten können Opfer, Beschützer, Täter oder in einem Konflikt mehreres davon sein. Demokratische Kontrolle, humanitäres Völkerrecht, Ausbildung, Untersuchung und persönliche Verantwortung sollen verhindern, dass militärische Notwendigkeit zur Erlaubnis für Verbrechen wird.'],
 ['title'=>'„Wenn Krieg beginnt, gehe ich einfach weg.“','core'=>'Flucht kann ein rechtmäßiger und verständlicher Weg sein, um sich, Kinder oder abhängige Angehörige zu schützen. Überleben ist keine Feigheit. Zivilisten sind kein politisches Druckmittel. Schutzrechte hängen nicht von Zustimmung zu persönlichen Entscheidungen ab.','reply'=>'„Weggehen“ ist aber noch kein vollständiger Notfallplan. Mindestens fünf Hürden bleiben: rechtzeitig und legal ausreisen, trotz gestörter Flüge, Treibstoff-, Bahn- und Straßennetze eine Route finden, in einen Zielstaat einreisen dürfen, einen längeren Aufenthaltsstatus erhalten und für unbestimmte Zeit Wohnung, Einkommen, Gesundheit und Schule sichern. Die Ukraine zeigt mögliche Ausreisebeschränkungen im Kriegsrecht. Kanada zeigt die Unsicherheit am Ziel: Deutsche brauchen für Flugreisen meist Pass und eTA. Eine eTA garantiert keine Einreise. Asyl verlangt einen persönlichen Schutzgrund. Sonderprogramme können geändert oder beendet werden. Bei einem NATO-weiten Krieg könnten weit mehr Menschen fliehen als bisher. Niemand sollte sicher annehmen, ein weit entfernter Staat werde im nötigen Moment unbegrenzte Einreise-, Arbeits- und Bleiberechte schaffen.','evidence'=>'Die Ukraine begrenzte nach der Mobilisierung die Ausreise vieler wehrpflichtiger Männer. Kanada beendete 2023 neue Anträge für das CUAET-Sonderprogramm und begrenzte spätere Maßnahmen. EU-Forschung zeigt zudem: Rechtlicher Schutz garantiert kein bequemes Leben. Befragte geflüchtete Ukrainerinnen berichteten von Geldnot, unsicherem Wohnen, Ausbeutung und Gewalt. Die USA schoben 2026 ukrainische Männer im Rahmen des Einwanderungsrechts ab; einige kamen danach zu ukrainischen Rekrutierungsstellen. Das war keine pauschale Abschiebung nur wegen ihres wehrfähigen Alters.','uncertainty'=>'Ein Krieg zwischen Deutschland, NATO und Russland wäre ohne Beispiel. Weder geschlossene Grenzen noch großzügige Aufnahme lassen sich vorhersagen. Andere Staaten könnten neue Schutzwege schaffen. Artikel 5 verpflichtet zur Hilfe, aber jeder Verbündete wählt seine Maßnahmen. Er verspricht nicht, dass andere Soldaten jede Person ersetzen, die Deutschland verlässt. Schutz für Geflüchtete darf trotzdem nicht an Militärdienst gebunden werden. Die engere Schlussfolgerung lautet: Flucht kann nötig sein, ist aber weder sicher noch einfach oder dauerhaft garantiert. Dokumente, Treffpunkte, amtliche Evakuierungsinformation, nahe Schutzmöglichkeiten und ein rechtmäßiger Beitrag zur zivilen Vorsorge sind glaubwürdiger als nur ein weit entferntes Wunschziel.'],
 ['title'=>'„Russland hat kein Interesse an Deutschland.“','core'=>'Eine gezielte Besetzung Deutschlands ist nicht der direkteste oder notwendige Weg für russische Ziele.','reply'=>'In diesem Stresstest ist Deutschland als politischer Entscheider, NATO-Zentrum und Logistikdrehscheibe wichtig. Störungen könnten Zwang ausüben, ohne Gebiete erobern zu wollen.','evidence'=>'Deutsche und NATO-Planung behandeln Aufnahme, Versorgung und Verstärkung der Alliierten ausdrücklich als strategische Aufgaben.','uncertainty'=>'Absichten können sich ändern und nie sicher gelesen werden.'],
 ['title'=>'„Die NATO bedroht Russland.“','core'=>'Russische Verantwortliche können Erweiterung und alliierte Streitkräfte als Bedrohung wahrnehmen.','reply'=>'Wahrnehmung ist wichtig. Sie hebt aber die Selbstbestimmung der Nachbarstaaten nicht auf und rechtfertigt keinen Angriff. Die NATO beschreibt ihre Haltung als defensiv. Mitgliedsregierungen entscheiden gemeinsam.','evidence'=>'Nordatlantikvertrag und aktuelle NATO-Planung richten sich auf gemeinsame Verteidigung, nicht auf Eroberung.','uncertainty'=>'Ein Sicherheitsdilemma kann auch bei erklärter defensiver Absicht bestehen bleiben.'],
 ['title'=>'„Mehr Waffen bedeuten automatisch mehr Krieg.“','core'=>'Waffen können Wettrüsten verstärken und Eskalation zerstörerischer machen.','reply'=>'Die Wirkung hängt von Aufstellung und Anreizen ab. Defensive Abwehr, Transparenz und Bündniskontrolle können den erwarteten Gewinn eines Angriffs senken.','evidence'=>'Forschung zum Sicherheitsdilemma unterscheidet zwischen Angriffsvorteilen und erkennbar defensiver Aufstellung.','uncertainty'=>'Kein militärischer Aufbau wird von allen Akteuren gleich verstanden.'],
 ['title'=>'„Im Atomkrieg ist Verteidigung sinnlos.“','core'=>'Ein großer Atomkrieg wäre katastrophal. Zivilschutz kann ihn nicht kontrollierbar machen.','reply'=>'Verteidigung soll auch konventionellen Zwang verhindern und Eskalation unterhalb der nuklearen Schwelle halten. Vorsorge kann bei Stromausfällen und konventionellen Notfällen weiterhin Leben retten.','evidence'=>'Die NATO verbindet Abschreckung mit Widerstandskraft. BBK-Ratschläge gelten für viele Krisen und versprechen keinen vollständigen Schutz.','uncertainty'=>'Nukleare Eskalation bleibt ein existenzielles Restrisiko.'],
 ['title'=>'„Diplomatie ist die einzige Lösung.“','core'=>'Kriege enden politisch. Kommunikation und ausgehandelte Grenzen sind unverzichtbar.','reply'=>'Diplomatie wirkt innerhalb von Anreizen und Grenzen. Wenn eine Seite von Gewalt mehr Erfolg erwartet, können Gespräche allein einen Angriff nicht verhindern.','evidence'=>'Rüstungskontrolle war am stärksten, wenn sie mit Prüfung, Abschreckung und dauerhafter Kommunikation verbunden war.','uncertainty'=>'Die richtige Mischung hängt von Zeitpunkt und Gegenüber ab.'],
 ['title'=>'„Eine Berufsarmee reicht aus.“','core'=>'Moderne Streitkräfte brauchen gut ausgebildete, lang dienende Fachkräfte.','reply'=>'Eine lange Verteidigung braucht zusätzlich Reserve, Logistik, Medizin, Cyberfähigkeit, Infrastruktur und Unterstützung für alliierte Truppen. Fachkräfte bleiben der Kern. Größere Zahlen können aber ausgebildete Verstärkung verlangen.','evidence'=>'Deutsche Planung verteilt Aufgaben auf aktive Kräfte, Reserve, territoriale Verteidigung und zivile Akteure.','uncertainty'=>'Der wirkliche Personalbedarf hängt von Strategie, Technik und Lastenteilung im Bündnis ab.'],
 ['title'=>'„Wehrpflicht ist grundsätzlich undemokratisch.“','core'=>'Pflichtdienst greift stark in Freiheit ein und kann unfair sein.','reply'=>'Demokratische Berechtigung braucht Gesetz, nachgewiesene Notwendigkeit, Gleichheit, Gewissensschutz, Kontrolle, angemessene Bezahlung und echte Ausbildungskapazität.','evidence'=>'Das Grundgesetz schützt Kriegsdienstverweigerung und enthält einen Rahmen für Pflichtdienst.','uncertainty'=>'Auch ein gesetzliches Modell kann unverhältnismäßig oder schlecht gestaltet sein.'],
 ['title'=>'„Deutschland könnte einfach neutral bleiben.“','core'=>'Neutralität kann in bestimmten Lagen die Verwicklung in Bündniskonflikte verringern.','reply'=>'Deutschland ist geografisch und wirtschaftlich tief in EU und NATO eingebunden. Ein einseitiger Austritt beseitigt weder Infrastruktur-, Cyber- noch Erpressungsrisiken. Er würde große politische, vertragliche und militärische Kosten schaffen.','evidence'=>'Deutschland hat bindende Bündniszusagen und liegt im Zentrum europäischer Logistik und Märkte.','uncertainty'=>'Neutralität wirkt nur, wenn andere sie anerkennen und der Staat sich glaubwürdig selbst verteidigen kann.'],
];
foreach ($data['objections'] as $i => &$objection) $objection = array_replace($objection, $objectionText[$i]);
unset($objection);

$data['people']['title'] = 'Warum Verteidigung Menschen braucht';
$data['people']['roles'] = [
    'Aktive Streitkräfte für sofortige Einsätze und besondere Fachfähigkeiten',
    'Reserve für Verstärkung, Durchhaltefähigkeit und Ersatz',
    'Territoriale Verteidigung und Schutz verteidigungswichtiger Aufgaben',
    'Aufnahme und Logistik für Bewegungen der Alliierten',
    'Sanitätsdienst und Versorgung Verwundeter',
    'Cyberabwehr und sichere Kommunikation',
    'Zivilschutz und Fortführung wichtiger Dienste',
    'Ausbildung vor einer Krise, weil Fähigkeiten und Einheiten nicht spontan entstehen',
];
$data['people']['serviceDebate'] = [
    'title'=>'Dienst für Land und demokratische Gemeinschaft – welches Modell erfüllt welchen Zweck?',
    'intro'=>'Dienst bedeutet Verantwortung für die demokratische Gemeinschaft und die Menschen, die in ihr leben. Er bedeutet keinen blinden Gehorsam gegenüber einer Regierung und keiner ethnischen Vorstellung vom „Volk“. Militärische Bereitschaft, zivile Widerstandskraft und soziales Lernen sind berechtigte, aber unterschiedliche Ziele. Ein einziges Pflichtprogramm erreicht nicht automatisch alle drei.',
    'learning'=>'Gut gestalteter Dienst kann Begegnung zwischen sozialen Gruppen, praktische Verantwortung, Teamarbeit, Konfliktfähigkeit, Selbstständigkeit und berufliche Orientierung fördern. Deutsche Untersuchungen zu Freiwilligendiensten und zum früheren Zivildienst fanden solche Entwicklungen. Sie beweisen nicht, dass der Zwang selbst die Ursache war. Auswahl der Teilnehmenden, Qualität der Stelle, Betreuung und sinnvolle Aufgaben sind wichtig. Ein demokratischer Staat darf Lernen ermöglichen, aber junge Erwachsene nicht politisch erziehen oder disziplinieren wollen.',
    'models'=>[
        ['title'=>'Klassisches deutsches Modell: Wehrdienst plus Ersatzdienst für Verweigerer','scope'=>'Im traditionellen Rahmen von Artikel 12a können Männer zum Wehrdienst einberufen werden. Anerkannte Kriegsdienstverweigerer leisten zivilen Ersatzdienst. Es ist keine gleiche Pflicht für alle Geschlechter.','purpose'=>'Hauptzweck sind militärisches Personal und Reserve. Der zivile Weg schützt die Gewissensfreiheit und kann soziale Einrichtungen unterstützen.','benefit'=>'Planbarere militärische Aufnahme, ausgebildete Reserve und praktische Diensterfahrung. Der frühere Zivildienst konnte soziale Fähigkeiten fördern und Kontakt zu Pflegearbeit und anderen Lebenswelten schaffen.','risk'=>'Ungleichheit zwischen Geschlechtern, zufällige Auswahl, spätere Ausbildung und Arbeit, Druck auf Gewissensentscheidungen sowie der Missbrauch billiger Pflichtkräfte als Ersatz für Fachpersonal. Ohne Ausbilder, Material und sinnvolle Stellen entstehen Wartezeit, Frust und wenig Sicherheit.','law'=>'Die Rückkehr zum verfassungsrechtlichen Wehrdienst ist rechtlich näher als eine neue allgemeine Bürgerpflicht. Fairness, Verhältnismäßigkeit, Auswahl und echte Kapazität brauchen trotzdem ein neues politisches und gesetzliches Konzept.','judgement'=>'Dieses Modell passt besser zu einer klar nachgewiesenen militärischen Personallücke. In seiner klassischen Form ist es jedoch sozial ungleich und kein allgemeines Bildungsprogramm.'],
        ['title'=>'Allgemeines Gesellschaftsjahr: militärische, zivile oder soziale Wahl für alle Geschlechter','scope'=>'Jeder junge Erwachsene würde für begrenzte Zeit dienen. Es gäbe eine echte Wahl zwischen Bundeswehr, Zivilschutz, Rettung, Gesundheit und Pflege, sozialen, ökologischen oder anderen anerkannten Aufgaben.','purpose'=>'Verantwortung gerechter teilen, militärische und zivile Widerstandskraft stärken, Begegnung schaffen und Lernen sowie Berufsorientierung ermöglichen.','benefit'=>'Beteiligung aller Geschlechter, ein größerer Pool für zivile Krisen und möglicherweise mehr Kontakt zwischen Klassen, Regionen und Herkunftsgruppen. Sinnvolle Arbeit und gute Begleitung können Teamarbeit, Mitgefühl, Selbstvertrauen und soziale Fähigkeiten stärken.','risk'=>'Starker Eingriff in Freiheit und Lebensplanung. Jedes Jahr wären Hunderttausende sinnvolle, betreute und zusätzliche Stellen nötig. Ausnahmen und Strafen können Ungleichheit vergrößern. Unfreiwillige Kräfte können Einrichtungen belasten. Pflichtarbeit kann reguläre Stellen verdrängen oder Unterfinanzierung in der Pflege verdecken. Die Bundeswehr erhält keine sichere Zahl, wenn zu wenige sie wählen.','law'=>'Nach der rechtlichen Prüfung des Bundestags verlangt die überwiegende Meinung eine Verfassungsänderung. Europäische und internationale Verbote von Zwangsarbeit bleiben eine hohe Hürde, besonders bei einer zwölfmonatigen allgemeinen Pflicht.','judgement'=>'Das Ziel ist breiter und gleicher. Rechtlich und organisatorisch ist es aber viel schwieriger. Es ist ein eigenes gesellschaftspolitisches Projekt, keine schnelle Antwort auf einen akuten militärischen Mangel.'],
    ],
    'enforcementTitle'=>'Der Praxistest – wo eine attraktive Idee scheitern kann',
    'enforcement'=>[
        'Einen konkreten öffentlichen Bedarf und eine passende Dauer nennen. „Charakterbildung“ ist als unklare Begründung nicht genug.',
        'Echte Wahlmöglichkeiten, Gewissensschutz, Härtefallausnahmen und erreichbaren Rechtsschutz anbieten.',
        'Die Pflicht über Geschlechter und soziale Gruppen gleich anwenden. Sonst belohnt die Auswahl Einfluss und belastet Menschen mit weniger Möglichkeiten.',
        'Genug bezahlen für Selbstständigkeit, Rente und Sozialschutz. Ausbildung, Studienplätze und Arbeitsverhältnisse sichern.',
        'Qualifizierte Betreuung, Schutzkonzepte, Unterkunft und Ausrüstung finanzieren, bevor ein Jahrgang einberufen wird.',
        'Pflichtkräfte nur zusätzlich und mit Lernziel einsetzen. Sie dürfen Fachkräfte in Pflege, Rettung oder Militär nie billig ersetzen.',
        'Strafen müssen verhältnismäßig sein. Harte Durchsetzung kann mehr Ungerechtigkeit und Ablehnung als Zusammenhalt schaffen.',
        'Kompetenzgewinn, öffentlichen Nutzen, späteres Ehrenamt und Verteilungswirkung mit einer freiwilligen Vergleichsgruppe prüfen.',
    ],
    'conclusion'=>'Meine Einschätzung: Zuerst attraktive Freiwilligendienste ausbauen und die Ausbilder, Stellen und Reservestrukturen schaffen, die jedes Modell braucht. Bleibt danach eine nachgewiesene militärische Lücke, lässt sich ein bedarfsgerechter und geschlechtergleicher Verteidigungsdienst mit echter ziviler Alternative leichter begründen als ein allgemeines Jahr, das vor allem moralische Erziehung verspricht. Ein allgemeines Gesellschaftsjahr braucht eine eigene Verfassungs- und Sozialdebatte.',
    'sources'=>$data['people']['serviceDebate']['sources'],
];
$data['people']['refusalParadox'] = [
    'title'=>'Die Ungleichheit der Verweigerung: Schützt ein künftiger Machthaber das heutige Recht auf Nein?',
    'text'=>'Eine freie Gesellschaft erlaubt Protest gegen Krieg und die Verweigerung des Dienstes mit der Waffe. Eine expansionistische autoritäre Ordnung muss diese Zurückhaltung nicht erwidern. Die unangenehme Gegenfrage lautet: Kann die Ablehnung jedes Beitrags zur demokratischen Selbstverteidigung heute Bedingungen fördern, unter denen dieselbe Person später weder protestieren noch einen fremden Expansionsdienst verweigern darf? Dieses Risiko spricht für demokratische Verteidigungsfähigkeit. Es hebt Gewissensschutz nicht auf und beweist nicht, dass militärische Eskalation klug ist.',
    'evidence'=>'Die UN dokumentierte russische Einberufungen auf der besetzten Krim und Hindernisse beim Antrag auf zivilen Ersatzdienst. Aktuelle EUAA-Berichte beschreiben Druck auf russische Wehrpflichtige zum Vertragsabschluss sowie Haftgefahr bei Verweigerung und Desertion.',
    'limit'=>'Das ist ein Risikomechanismus, keine Prognose für Deutschland. Er darf nicht genutzt werden, um Pazifisten, Russen als Bevölkerung oder alle Gegner einer Dienstpflicht abzuwerten. Die demokratische Antwort verbindet Verteidigungsfähigkeit mit einem wirksamen Recht auf Gewissen – nicht mit grenzenlosem Zwang.',
    'sources'=>$data['people']['refusalParadox']['sources'],
];
$modelText = [
 ['model'=>'Nur Berufsstreitkräfte','effect'=>'Hohe Fachqualität, aber begrenzter schneller Aufwuchs','speed'=>'Langsamer Ausbau','cost'=>'Hohe Personalkosten','freedom'=>'Geringer Eingriff','fairness'=>'Freiwillig','specialists'=>'Stark','reserve'=>'Begrenzt, wenn sie nicht extra aufgebaut wird','labour'=>'Geringste direkte Störung'],
 ['model'=>'Freiwilliger Dienst','effect'=>'Guter Einstieg und Reservepool, wenn attraktiv','speed'=>'Hängt von Gewinnung ab','cost'=>'Mittlere bis hohe Anreize','freedom'=>'Freiwillig','fairness'=>'Selbstauswahl','specialists'=>'Gemischt','reserve'=>'Mittleres Potenzial','labour'=>'Selbst gewählte Unterbrechung'],
 ['model'=>'Bedarfsgerechte Wehrpflicht','effect'=>'Schließt nachgewiesene Lücken gezielt','speed'=>'Mittel, sobald Infrastruktur besteht','cost'=>'Ausbildungskapazität nötig','freedom'=>'Ausgewählter Eingriff','fairness'=>'Auswahl kann umstritten sein','specialists'=>'Nur teilweise geeignet','reserve'=>'Gut bei wirksamer Nachbetreuung','labour'=>'Ungleich verteilte Wirkung'],
 ['model'=>'Allgemeine Wehrpflicht','effect'=>'Großer möglicher Pool','speed'=>'Langsam, bis das Ausbildungssystem groß genug ist','cost'=>'Hohe Systemkosten','freedom'=>'Starker Eingriff','fairness'=>'Breite Pflicht, Ausnahmen bleiben','specialists'=>'Kein guter Ersatz für Berufslaufbahnen','reserve'=>'Hohes Potenzial','labour'=>'Breite Wirkung auf Bildung und Arbeit'],
 ['model'=>'Allgemeiner Gesellschaftsdienst mit militärischer und ziviler Wahl','effect'=>'Kann Verteidigung und zivile Widerstandskraft stärken','speed'=>'Schwierig aufzubauen','cost'=>'Sehr hoher Verwaltungsaufwand','freedom'=>'Starker Eingriff mit Wahlmöglichkeit','fairness'=>'Am breitesten, wenn wirklich allgemein','specialists'=>'Braucht getrennte Berufslaufbahnen','reserve'=>'Militärisch gemischt, zivil starkes Potenzial','labour'=>'Breite Wirkung auf Bildung und Arbeit'],
];
foreach ($data['people']['models'] as $i => &$model) $model = array_replace($model, $modelText[$i]);
unset($model);
$data['people']['safeguards'] = ['Verfassungsrecht auf Kriegsdienstverweigerung','Gleichbehandlung und glaubwürdige Fairness','Angemessene Bezahlung und sozialer Schutz','Schutz von Ausbildung, Studium und Beschäftigung','Genügend Ausbilder, Unterkünfte und Ausrüstung vor der Einberufung','Nachgewiesener Personalbedarf statt symbolischer Zahlen'];

$data['conscriptionMap'] = array_replace($data['conscriptionMap'], [
    'title'=>'Ist Wehrpflicht demokratisch? Ein Weltvergleich',
    'statusDate'=>'Stand der Wehrpflicht: Juli 2026 · Einordnung der Regierungsform: V-Dem 2024',
    'definition'=>'Die Karte zählt einen aktiven oder tatsächlich durchgesetzten Militärdienst. Dazu gehören auch Auswahl-, Quoten- und Losverfahren. Eine reine Registrierung, ausgesetzter Dienst und gesetzliche Notfallrechte ohne aktuelle Einberufung gelten als keine aktive Wehrpflicht.',
    'democracyMethod'=>'„Demokratie“ umfasst bei V-Dem liberale und elektorale Demokratien. Elektorale und geschlossene Autokratien stehen in der Gruppe „nicht als Demokratie eingeordnet“. Graubereiche folgen der besten veröffentlichten V-Dem-Schätzung. Das ist eine Messentscheidung und kein endgültiges Urteil über ein Land.',
    'conclusion'=>'Die Karte beantwortet eine beschreibende, keine moralische Frage: Wehrpflicht gibt es in Demokratien und Autokratien. In einer Demokratie braucht sie trotzdem einen nachgewiesenen Sicherheitszweck, Gesetz und Parlamentskontrolle, Verhältnismäßigkeit, faire Auswahl, sozialen Schutz, gerichtliche Prüfung und ein wirksames Recht auf Kriegsdienstverweigerung. Eine gesetzlich beschlossene Pflicht ist ohne diese Schutzmechanismen nicht automatisch demokratisch berechtigt.',
    'countryNotes'=>[
      'Germany'=>'Keine aktive Wehrpflicht: zunächst freiwilliger Dienst, verpflichtende Registrierung und Musterung sowie eine parlamentarische Möglichkeit zur späteren Einberufung.',
      'Croatia'=>'Verpflichtende militärische Grundausbildung wurde 2026 wieder aufgenommen.',
      'Mexico'=>'Ein Teil wird durch Los ausgewählt.',
      'Norway'=>'Ausgewähltes, geschlechtsneutrales System; nur ein kleiner Teil jedes Jahrgangs wird einberufen.',
      'Ukraine'=>'Im Krieg bestehen Pflichtdienst und Mobilisierung. V-Dem ordnete die Ukraine für 2024 als elektorale Autokratie ein, weil demokratische Institutionen während des Krieges eingeschränkt waren.',
    ],
]);
$data['preventionMeasures'] = [
 ['category'=>'Militärisch','items'=>['Europäische defensive Fähigkeiten, Luft- und Raketenabwehr, Munition und Ersatzteile erhalten','Reserve und territoriale Verteidigung ausbilden und alliierte Verstärkung üben','Nach einem begrenzten Angriff einen schnellen vollendeten Gebietsverlust verhindern']],
 ['category'=>'Diplomatisch','items'=>['Ukraine unterstützen und glaubwürdige rote Linien erklären, ohne Gewissheit vorzutäuschen','Kanäle für Rüstungskontrolle, Vorfallvermeidung und Krisenkommunikation offenhalten','NATO-Beratung beschleunigen und zugleich Kommunikation zur Begrenzung der Eskalation bewahren']],
 ['category'=>'Wirtschaftlich','items'=>['Erneuerbare Erzeugung, Netze, Speicher, Effizienz und europäische Verbindungen ausbauen, um fossile Importabhängigkeit und Preisschocks zu senken','Kritische Rohstoff- und Technikabhängigkeiten breit verteilen, statt nur eine einzelne Quelle durch eine andere zu ersetzen','Gemeinsam europäisch beschaffen, Lieferketten stärken und Haushalte sowie Unternehmen bei Störungen gezielt helfen']],
 ['category'=>'Gesellschaftlich','items'=>['Desinformation transparent aufdecken, ohne offene Debatte zu unterdrücken','Unternehmen, Kommunen, Zivilgesellschaft und Medien an Übungen beteiligen','Zusammenhalt schützen und Lasten der Vorsorge fair verteilen']],
 ['category'=>'Zivilschutz','items'=>['Kritische Infrastruktur und Kommunikation schützen und Ersatzwege schaffen','Warnsysteme, Notversorgung und Betriebsfähigkeit der Krankenhäuser ausbauen','Haushaltsvorsorge nach BBK fördern und Menschen unterstützen, die sie nicht bezahlen können']],
];
$data['historicalCases'] = [
 ['case'=>'Europa vor 1914','use'=>'Warnung vor Mobilisierungsdruck, Bündnisdynamik und Sicherheitsdilemma.','limit'=>'Keine Vorlage für die nukleare NATO und das heutige Europa.'],
 ['case'=>'Beschwichtigung in den 1930er-Jahren','use'=>'Warnung, dass Zugeständnisse und verspätete Bereitschaft revisionistische Ziele nicht immer befriedigen.','limit'=>'Ideologie und Lage des nationalsozialistischen Deutschlands sind nicht mit jedem heutigen Gegner gleichzusetzen.'],
 ['case'=>'Abschreckung und Rüstungskontrolle im Kalten Krieg','use'=>'Zeigt, dass Verteidigung, Kommunikation, Kontrolle und ausgehandelte Grenzen zusammen möglich sind.','limit'=>'Das Ausbleiben eines direkten Kriegs der Supermächte beweist nicht, dass das System sicher oder wiederholbar war.'],
];
$data['closing'] = [
 'headline'=>'Verteidigungsfähig sein, damit wir nicht kämpfen müssen.',
 'explanation'=>'Abschreckung wirkt, wenn ein möglicher Angreifer erkennt, dass er politische Ziele weder schnell noch zu tragbaren Kosten erreichen kann. Verteidigungsfähigkeit ersetzt Diplomatie nicht. Sie gibt ihr Rückhalt und senkt den Anreiz, politische Ziele mit Gewalt durchzusetzen.',
 'balance'=>'Frieden braucht mehr als Waffen: belastbare Bündnisse, Diplomatie, Rüstungskontrolle, wirtschaftliche Widerstandskraft, gesellschaftlichen Zusammenhalt und glaubwürdige defensive Fähigkeiten.',
];
$findingText = [
 'nato-treaty'=>'Jeder Verbündete hilft einem angegriffenen Mitglied mit den Maßnahmen, die er für nötig hält. Dazu kann militärische Gewalt gehören.',
 'nato-article5'=>'Erklärt gemeinsame Verteidigung, Beratung und nationale Maßnahmen.',
 'nato-east'=>'Dokumentiert multinationale Vorwärtsverteidigung und Verstärkung der östlichen Verbündeten.',
 'nato-hybrid'=>'Hybride Methoden verbinden militärische und nichtmilitärische, offene und verdeckte Mittel. Ein hybrider Angriff kann Beratungen über Artikel 5 auslösen.',
 'nato-deterrence'=>'Die erklärte NATO-Haltung verbindet Abwehr, Verstärkung, Widerstandskraft sowie konventionelle und nukleare Abschreckung.',
 'nato-russia'=>'Dokumentiert die Verschlechterung der Beziehungen und die NATO-Bewertung russischer Handlungen.',
 'eu-hybrid'=>'Nennt Sabotage, Störung von Infrastruktur, Cyberangriffe, Informationsmanipulation und Einfluss auf Wahlen und beschreibt Werkzeuge der EU.',
 'bbk'=>'Persönliche Vorsorge soll zur eigenen Lage passen. Zehn Tage sind das Ziel; schon drei Tage helfen. Die Hinweise behandeln Ausfälle, Warnungen, psychische Gesundheit und Desinformation.',
 'op-de'=>'Beschreibt öffentlich territoriale Verteidigung, Unterstützung der Alliierten und Deutschlands Rolle als Logistikzentrum, ohne operative Details zu veröffentlichen.',
 'national-security'=>'Versteht Sicherheit als gemeinsame Aufgabe von Staat, Wirtschaft und Gesellschaft auf Grundlage von Völkerrecht und Menschenrechten.',
 'bfv'=>'Amtliche Berichte behandeln russische Spionage, Cyberaktivität, Einfluss und Sabotagerisiken. Sie beweisen die fiktive Eskalationskette nicht.',
 'osce'=>'Transparenz, Meldung, Prüfung und Beratung helfen, militärische Fehlwahrnehmung zu verringern.',
 'sipri'=>'Nukleare Modernisierung und schwächere Rüstungskontrolle machen die Begrenzung von Eskalationsrisiken wichtiger.',
 'jervis'=>'Erklärt, wie Angriffs- oder Verteidigungsvorteile und die erkennbare Ausrichtung von Streitkräften Spiralen oder Stabilität fördern.',
 'basic-law'=>'Schützt Kriegsdienstverweigerung und bildet den verfassungsrechtlichen Rahmen für Pflichtdienst.',
 'bverfg-soldiers'=>'Das Gericht hob Verurteilungen auf, weil die Meinungsfreiheit nicht ausreichend beachtet worden war. Es erklärte die Gleichsetzung von Soldaten und Mördern ausdrücklich nicht für rechtmäßig.',
 'inner-leadership'=>'Beschreibt Soldaten als Staatsbürger in Uniform, die an das Grundgesetz gebunden sind. Blinder Gehorsam wird abgelehnt; verbrecherische Befehle müssen verweigert werden.',
 'bundestag-general-duty'=>'Nach überwiegender Rechtsmeinung braucht eine allgemeine Dienstpflicht eine Verfassungsänderung. Verbote von Zwangsarbeit in europäischem und internationalem Recht bleiben hohe Hürden.',
 'bmfsfj-voluntary-evaluation'=>'Langzeitbefragungen untersuchten persönliche und soziale Fähigkeiten, Orientierung und spätere Wirkungen bei Freiwilligen. Ergebnisse lassen sich nicht einfach auf Pflichtteilnehmende übertragen.',
 'bmfsfj-civilian-socialisation'=>'Die Forschung begleitete persönliche, soziale und geschlechtsbezogene Entwicklung vor, während und nach dem früheren Zivildienst.',
 'euaa-russia-service'=>'Dokumentiert Pflichtdienst, berichteten Druck zum Abschluss militärischer Verträge, Dienstbedingungen und Haftstrafen bis zu fünfzehn Jahren bei Desertion im Krieg.',
 'ohchr-crimea-conscription'=>'Dokumentiert russische Einberufung auf der besetzten Krim sowie Hindernisse und Drohungen bei Anträgen auf zivilen Ersatzdienst.',
 'iea-energy'=>'Die Energiekrise zeigte die Risiken fossiler Importe. Ein schnellerer Umbau zu sauberer Energie kann Sicherheit, Bezahlbarkeit, Wettbewerbsfähigkeit und Klimaschutz stärken.',
 'eprs-conscription'=>'Vergleicht europäische Wehrpflichtmodelle sowie Unterschiede bei Größe, Dauer, Reserve und demokratischen Folgen.',
 'croatia-service'=>'Dokumentiert das Gesetz von 2025 und den Beginn verpflichtender Einberufungen 2026.',
 'vdem-regimes'=>'Liefert die vier Gruppen liberale Demokratie, elektorale Demokratie, elektorale Autokratie und geschlossene Autokratie für die Kartenfarben.',
 'conscription-global'=>'Bietet einen weltweiten Überblick zu aktiver, ausgewählter, ausgesetzter und freiwilliger Dienstform. Es gibt kein vollständig aktuelles amtliches Weltregister.',
 'unhcr-refugee-convention'=>'Erklärt das Verbot der Zurückweisung und Mindestschutzrechte. Schutzrecht garantiert nicht automatisch dauerhaften Aufenthalt im gewünschten Land.',
 'ohchr-ukraine-exit'=>'Dokumentiert Ausreisebeschränkungen im Zusammenhang mit Mobilisierung sowie Probleme durch fehlende Dokumente und gestörten Verkehr.',
 'canada-entry'=>'Für visumfreie Flugreisen sind normalerweise Pass und eTA nötig. Eine eTA garantiert keine Einreise; die Grenzbehörde entscheidet.',
 'canada-ukraine-measures'=>'Kanadas Sonderaufnahme für Ukrainer war zeitlich begrenzte Politik mit Fristen und wechselnden Regeln, kein automatisches Kriegsrecht für jede Nationalität.',
 'fra-ukraine-flight'=>'Befragte Ukrainerinnen berichteten trotz formaler Schutzrechte von Geldnot, unsicherem Wohnen, Ausbeutung, Belästigung und fehlender psychologischer Hilfe.',
 'cnn-us-ukraine-removals'=>'Berichtet über bestimmte US-Abschiebungen und spätere ukrainische Rekrutierungsverfahren. Es beweist keine allgemeine Abschiebung aller ukrainischen Männer nur wegen ihres Alters.',
 'masala'=>'Das Buch regt die Gegenfrage an. Die sieben Phasen von RealityCheck sind unabhängig und werden nicht als Prognose des Autors dargestellt.',
];
foreach ($data['sources'] as &$source) {
    if (isset($findingText[$source['id']])) $source['finding'] = $findingText[$source['id']];
}
unset($source);
return $data;
