<?php
declare(strict_types=1);

return [
 'digital-government'=>[
  'problemDetail'=>[
   'en'=>['A digital service is not just a PDF on a website. Citizens and firms need one clear process from application to decision. Today, data are often requested again because registers cannot exchange them safely. This costs time on both sides and makes errors more likely.','The difficult part is organisational. Federal, state and local authorities use different laws, standards and software. A new portal alone cannot solve this. Germany needs common rules for identity, data quality, responsibility and appeals.'],
   'de'=>['Ein digitaler Dienst ist nicht nur ein PDF auf einer Webseite. Bürger und Unternehmen brauchen einen klaren Weg vom Antrag bis zur Entscheidung. Heute werden Daten oft erneut verlangt, weil Register sie nicht sicher austauschen können. Das kostet auf beiden Seiten Zeit und erhöht das Fehlerrisiko.','Der schwierige Teil ist die Organisation. Bund, Länder und Kommunen nutzen unterschiedliche Gesetze, Standards und Programme. Ein neues Portal allein löst das nicht. Deutschland braucht gemeinsame Regeln für Identität, Datenqualität, Verantwortung und Widerspruch.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany is strong in industrial technology but weaker in digital public services. Low eID use means many services still need paper, a visit to an office or a second identity check. Municipalities also lack specialists and stable funding for common systems.','Progress should be measured by completed services, not by the number of online forms. Useful indicators are processing time, repeated data requests, digital completion rate, accessibility and the number of successful appeals.'],
   'de'=>['Deutschland ist stark bei Industrietechnik, aber schwächer bei digitalen Verwaltungsleistungen. Die geringe eID-Nutzung führt dazu, dass viele Vorgänge weiterhin Papier, einen Behördengang oder eine zweite Identitätsprüfung brauchen. Kommunen fehlen zudem Fachkräfte und verlässliche Mittel für gemeinsame Systeme.','Fortschritt sollte an abgeschlossenen Leistungen gemessen werden, nicht an der Zahl der Onlineformulare. Sinnvolle Kennzahlen sind Bearbeitungszeit, wiederholte Datenabfragen, digital abgeschlossene Vorgänge, Barrierefreiheit und erfolgreiche Widersprüche.']
  ],
  'outlook'=>['en'=>'Without common infrastructure, Germany may have more portals by 2036 but still keep the same slow processes behind them. With shared registers and clear ownership, routine cases could become much faster while complex cases keep human review.','de'=>'Ohne gemeinsame Infrastruktur könnte Deutschland 2036 mehr Portale haben, aber dahinter weiter dieselben langsamen Abläufe. Mit verbundenen Registern und klarer Verantwortung können Standardfälle deutlich schneller werden, während schwierige Fälle menschlich geprüft bleiben.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Estonia rebuilt administration around a secure digital identity and connected registers.','de'=>'Estland baute seine Verwaltung um eine sichere digitale Identität und verbundene Register auf.'],'implementation'=>['en'=>'The X-Road exchange layer lets authorities share approved data without creating one giant central database. Access is logged and citizens can see many uses of their data.','de'=>'Die Austauschschicht X-Road erlaubt Behörden, freigegebene Daten zu teilen, ohne eine einzige riesige Zentraldatenbank zu schaffen. Zugriffe werden protokolliert und Bürger können viele Datennutzungen sehen.'],'results'=>['en'=>'Many routine services can be completed online. The important result is less repeated data entry, not only a high number of websites.','de'=>'Viele Standardleistungen können online abgeschlossen werden. Entscheidend ist weniger doppelte Dateneingabe und nicht nur eine hohe Zahl von Webseiten.'],'transfer'=>['en'=>'Germany can use the architecture, but it needs federal agreements, strong cyber security and clear limits on data use.','de'=>'Deutschland kann die Architektur nutzen, braucht dafür aber föderale Vereinbarungen, starke Cybersicherheit und klare Grenzen der Datennutzung.']],
   ['starting'=>['en'=>'Denmark and Finland had many separate public bodies and needed a common way to reach services.','de'=>'Dänemark und Finnland hatten ebenfalls viele getrennte Behörden. Bürger sollten staatliche Leistungen trotzdem über einen gemeinsamen Zugang finden können.'],'implementation'=>['en'=>'Shared login, message boxes, data exchange and service portals became basic public infrastructure. Authorities were required to design services around life events.','de'=>'Eine gemeinsame Anmeldung, sichere digitale Postfächer, Datenaustausch und zentrale Serviceportale wurden zur staatlichen Grundausstattung. Leistungen werden aus Sicht konkreter Lebenssituationen geplant, etwa Umzug, Geburt oder Unternehmensgründung.'],'results'=>['en'=>'People face fewer departmental borders. Digital use is high, but support and non-digital access remain necessary.','de'=>'Bürger müssen Zuständigkeitsgrenzen seltener selbst überwinden. Die digitale Nutzung ist hoch. Persönliche Unterstützung und ein nichtdigitaler Zugang bleiben dennoch notwendig.'],'transfer'=>['en'=>'Germany should finance shared components once and reuse them. Municipalities need migration help instead of another unfunded duty.','de'=>'Deutschland sollte gemeinsame technische Bausteine zentral finanzieren und allen Behörden zur Verfügung stellen. Kommunen brauchen Personal und Geld für die Umstellung; eine neue Pflicht ohne Unterstützung würde die Probleme nur verlagern.']],
  ],
  'prerequisites'=>['en'=>['One responsible owner for each end-to-end service','Common register, identity and accessibility standards','Independent data protection, security tests and a right to human review'],'de'=>['Eine verantwortliche Stelle für den gesamten Vorgang','Gemeinsame Standards für Register, Identität und Barrierefreiheit','Unabhängiger Datenschutz, Sicherheitstests und Recht auf menschliche Prüfung']],
 ],
 'bureaucracy'=>[
  'problemDetail'=>[
   'en'=>['Bureaucracy has two sides. Rules protect safety, workers, consumers and the environment. The problem is not regulation itself, but repeated evidence, unclear responsibility and procedures that do not match the real risk.','A company can wait because several authorities work one after another. A faster system lets them work in parallel, uses one trusted data set and makes a final decision within a clear period.'],
   'de'=>['Bürokratie hat zwei Seiten. Regeln schützen Sicherheit, Beschäftigte, Verbraucher und Umwelt. Das Problem ist nicht jede Regulierung, sondern doppelte Nachweise, unklare Verantwortung und Verfahren, die nicht zum wirklichen Risiko passen.','Ein Unternehmen wartet oft, weil mehrere Behörden nacheinander arbeiten. Ein schnelleres System lässt sie parallel prüfen, nutzt einen verlässlichen Datensatz und trifft innerhalb einer klaren Frist eine endgültige Entscheidung.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany’s federal structure allows local knowledge but can create different forms and interpretations. Small firms carry a larger burden because they have fewer legal and administrative staff. Slow permits also block housing, grids and industrial renewal.','Good reform should publish the full process time, including pauses and requests for new documents. It should also measure whether faster decisions later cause more legal errors or environmental damage.'],
   'de'=>['Deutschlands Föderalismus ermöglicht Ortskenntnis, kann aber unterschiedliche Formulare und Auslegungen erzeugen. Kleine Firmen tragen eine größere Last, weil sie weniger Rechts- und Verwaltungspersonal haben. Langsame Genehmigungen bremsen auch Wohnungen, Netze und industrielle Erneuerung.','Gute Reform veröffentlicht die gesamte Verfahrensdauer einschließlich Pausen und Nachforderungen. Sie misst außerdem, ob schnellere Entscheidungen später mehr Rechtsfehler oder Umweltschäden verursachen.']
  ],
   'outlook'=>['en'=>'If Germany only removes individual rules, new duties may soon replace them. By 2036 the stronger approach is a permanent system that checks total burden, results and legal quality.','de'=>'Wenn Deutschland nur einzelne Vorschriften streicht, entstehen an anderer Stelle schnell neue Pflichten. Sinnvoller ist ein dauerhaftes Verfahren: Es erfasst den gesamten Verwaltungsaufwand, prüft die tatsächliche Wirkung und achtet zugleich auf Rechtssicherheit.'],
  'caseDetails'=>[
    ['starting'=>['en'=>'Denmark and the Netherlands wanted to reduce repeated contact between firms and public bodies.','de'=>'Dänemark und die Niederlande wollten vermeiden, dass Unternehmen dieselben Angaben mehrfach bei verschiedenen Behörden einreichen müssen.'],'implementation'=>['en'=>'Business portals combine registration, reporting and guidance. Core company data can be reused, and policy makers measure administrative cost.','de'=>'Zentrale Unternehmensportale bündeln Gründung, Pflichtmeldungen und Beratung. Bereits geprüfte Firmendaten dürfen von anderen zuständigen Behörden erneut genutzt werden. Zusätzlich wird gemessen, wie viel Zeit und Geld staatliche Pflichten verursachen.'],'results'=>['en'=>'Routine duties become easier to understand and complete. Benefits are smaller when local permits still use separate systems.','de'=>'Standardmeldungen werden verständlicher und schneller. Der Vorteil bleibt jedoch begrenzt, solange kommunale Genehmigungen über getrennte Verfahren und Programme laufen.'],'transfer'=>['en'=>'Germany needs a cross-level service promise and shared data, not only a federal portal.','de'=>'Für Deutschland reicht ein Bundesportal nicht aus. Bund, Länder und Kommunen müssen gemeinsame Datenstandards, Zuständigkeiten und verbindliche Bearbeitungsziele vereinbaren.']],
    ['starting'=>['en'=>'New Zealand and Switzerland wanted rules that stay useful after political attention moves on.','de'=>'Neuseeland und die Schweiz wollten verhindern, dass neue Vorschriften dauerhaft bestehen bleiben, obwohl sie ihr Ziel verfehlen oder unnötige Kosten verursachen.'],'implementation'=>['en'=>'Impact checks, consultation and later reviews compare expected and real effects. Proportionate tests avoid treating every small rule like a major law.','de'=>'Vor der Einführung werden erwartete Folgen geprüft und Betroffene angehört. Nach einigen Jahren wird verglichen, ob die Regel tatsächlich wirkt. Kleine Änderungen erhalten eine kürzere Prüfung als große Gesetze.'],'results'=>['en'=>'Costs and conflicts become visible earlier. Quality depends on honest data and independent challenge.','de'=>'Kosten, Nebenwirkungen und Interessenkonflikte werden früher sichtbar. Das funktioniert nur mit verlässlichen Daten und einer Prüfstelle, die auch der Regierung widersprechen kann.'],'transfer'=>['en'=>'Germany can add review dates and public scorecards, but should not create a second layer of paperwork.','de'=>'Deutschland kann für wichtige Regeln feste Prüftermine und öffentlich verständliche Ergebnisberichte einführen. Die Kontrolle muss schlank bleiben und darf nicht selbst neue Bürokratie erzeugen.']],
  ],
  'prerequisites'=>['en'=>['Parallel rather than sequential review where legally possible','One shared file and one lead authority','Public reporting on speed, errors and later court decisions'],'de'=>['Parallele statt nacheinander erfolgende Prüfung, wo rechtlich möglich','Eine gemeinsame Akte und eine federführende Behörde','Öffentliche Berichte über Tempo, Fehler und spätere Gerichtsentscheidungen']],
 ],
 'economy'=>[
  'problemDetail'=>[
   'en'=>['Productivity means producing more value with the same work and resources. It is the main long-term source of higher wages when the workforce stops growing. Germany’s challenge is not a lack of research, but slow use of new knowledge across the wider economy.','Young firms often struggle to grow, while established firms face expensive energy, slow infrastructure and uncertain rules. A successful policy must improve competition and investment instead of protecting every existing business model.'],
   'de'=>['Produktivität bedeutet, mit derselben Arbeit und denselben Mitteln mehr Wert zu schaffen. Sie ist die wichtigste langfristige Quelle höherer Löhne, wenn die Zahl der Arbeitskräfte nicht mehr wächst. Deutschlands Problem ist nicht zu wenig Forschung, sondern die langsame Nutzung neuen Wissens in der breiten Wirtschaft.','Junge Unternehmen können oft nur schwer wachsen. Bestehende Firmen leiden unter teurer Energie, langsamer Infrastruktur und unsicheren Regeln. Erfolgreiche Politik muss Wettbewerb und Investitionen verbessern, statt jedes alte Geschäftsmodell zu schützen.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany still has strong industry, universities and skilled occupations. Weak points include low business entry, limited scale-up capital, slow public investment and large differences between regions.','The OECD package shows that no single reform creates the full gain. Better governance, labour incentives, infrastructure, research, childcare, education and pensions work together. The 0.8-point result is a model, not a promise.'],
   'de'=>['Deutschland hat weiterhin starke Industrie, Hochschulen und Fachberufe. Schwächen sind geringe Gründungsdynamik, wenig Wachstumskapital, langsame öffentliche Investitionen und große Unterschiede zwischen Regionen.','Das OECD-Paket zeigt: Keine einzelne Reform bringt den gesamten Gewinn. Bessere Verwaltung, Arbeitsanreize, Infrastruktur, Forschung, Betreuung, Bildung und Rente wirken zusammen. Der Wert von 0,8 Punkten ist ein Modell und kein Versprechen.']
  ],
   'outlook'=>['en'=>'By 2036, ageing makes productivity more important. Without wider technology use, public spending and living standards will compete more sharply. With successful diffusion, fewer workers can support high output and better services.','de'=>'Bis 2036 arbeiten voraussichtlich weniger Menschen. Deshalb muss jede Arbeitsstunde mehr Wert schaffen. Wenn neue Technik auch im Mittelstand und in der Verwaltung ankommt, können trotz kleinerer Erwerbsbevölkerung hohe Löhne und gute öffentliche Leistungen finanzierbar bleiben.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Switzerland and Ireland needed high-value activity despite small domestic markets.','de'=>'Die Schweiz und Irland brauchten trotz kleiner Binnenmärkte hochwertige Wirtschaftsaktivität.'],'implementation'=>['en'=>'They combined access to skilled people, research links, international firms and predictable institutions. Ireland also used low corporate tax, which is the least transferable part.','de'=>'Sie verbanden Zugang zu Fachkräften, Forschungsnetzwerke, internationale Unternehmen und verlässliche Institutionen. Irland nutzte auch niedrige Unternehmenssteuern; das ist der am wenigsten übertragbare Teil.'],'results'=>['en'=>'Both built strong export clusters. They also face housing pressure, regional concentration and dependence on international firms.','de'=>'Beide bauten starke Exportcluster auf. Gleichzeitig entstanden Wohnungsdruck, regionale Konzentration und Abhängigkeit von internationalen Firmen.'],'transfer'=>['en'=>'Germany should copy research transfer, skills and predictability, not a small-country tax model.','de'=>'Deutschland sollte Forschungstransfer, Qualifikation und Verlässlichkeit übernehmen, nicht das Steuermodell eines kleinen Landes.']],
    ['starting'=>['en'=>'South Korea and Singapore wanted to move from lower-cost production to advanced technology.','de'=>'Südkorea und Singapur wollten ihre Wirtschaft von günstiger Massenproduktion zu Forschung und anspruchsvoller Technologie weiterentwickeln.'],'implementation'=>['en'=>'Government coordinated education, research, infrastructure and selected industrial programmes over many years. Export pressure tested whether firms could compete.','de'=>'Über viele Jahre stimmte der Staat Bildungs-, Forschungs- und Infrastrukturpolitik auf ausgewählte Zukunftsbranchen ab. Der Wettbewerb auf Exportmärkten zeigte, ob die geförderten Unternehmen international bestehen konnten.'],'results'=>['en'=>'Technology capacity and income rose strongly. The model also created concentration, high pressure and risks of political favouritism.','de'=>'Technisches Wissen, Exporterfolge und Einkommen nahmen deutlich zu. Gleichzeitig konzentrierte sich wirtschaftliche Macht bei wenigen Unternehmen; außerdem bestand die Gefahr, dass politische Nähe über Förderung entschied.'],'transfer'=>['en'=>'Germany can set missions and evaluate them, but must keep competition, open procurement and exit rules for failed support.','de'=>'Deutschland kann klare technologische Ziele setzen und Programme regelmäßig bewerten. Förderung sollte offen vergeben und beendet werden, wenn messbare Erfolge ausbleiben. Wettbewerb muss erhalten bleiben.']],
  ],
  'prerequisites'=>['en'=>['Stable investment rules over more than one election period','Independent evaluation and an end date for weak support','Better links between research, medium-sized firms and growth finance'],'de'=>['Stabile Investitionsregeln über mehr als eine Wahlperiode','Unabhängige Bewertung und Enddatum für schwache Förderung','Bessere Verbindung von Forschung, Mittelstand und Wachstumsfinanzierung']],
 ],
 'tax'=>[
  'problemDetail'=>[
   'en'=>['A tax system must collect enough revenue, distribute burdens fairly and remain understandable. Germany often tries to reach social goals through many exceptions. This can make effective rates hard to see and rewards people who can afford advice.','High taxes and contributions on additional work can be especially important for low earners and a second earner in a couple. Reform must examine the whole household and transfer system, not only one tax rate.'],
   'de'=>['Ein Steuersystem muss genug Geld einnehmen, Lasten fair verteilen und verständlich bleiben. Deutschland verfolgt soziale Ziele oft mit vielen Ausnahmen. Dadurch sind wirkliche Belastungen schwer zu erkennen, und Menschen mit guter Beratung haben Vorteile.','Hohe Steuern und Beiträge auf zusätzliche Arbeit sind besonders für Geringverdienende und die zweite erwerbstätige Person eines Paares wichtig. Reformen müssen das gesamte Steuer- und Transfersystem betrachten, nicht nur einen Steuersatz.']
  ],
  'germanyDetail'=>[
   'en'=>['Joint taxation, social contributions and the withdrawal of benefits can create high marginal burdens. At the same time, municipalities need reliable revenue and ageing raises public costs.','A serious reform publishes effects by income, gender, family type and region. A simpler return is useful, but the distribution of the final burden matters more than the number of form fields.'],
   'de'=>['Zusammenveranlagung, Sozialbeiträge und der Wegfall von Leistungen können hohe Grenzbelastungen schaffen. Gleichzeitig brauchen Kommunen sichere Einnahmen, und die Alterung erhöht öffentliche Kosten.','Eine ernsthafte Reform zeigt Wirkungen nach Einkommen, Geschlecht, Familientyp und Region. Eine einfachere Erklärung ist hilfreich, aber die Verteilung der gesamten Last ist wichtiger als die Zahl der Formularfelder.']
  ],
  'outlook'=>['en'=>'By 2036, a smaller workforce will make work incentives and stable revenue more important at the same time. Tax cuts without financing would only move the burden into debt or weaker services.','de'=>'Bis 2036 macht eine kleinere Erwerbsbevölkerung Arbeitsanreize und stabile Einnahmen gleichzeitig wichtiger. Steuersenkungen ohne Finanzierung verschieben die Last nur in Schulden oder schwächere Leistungen.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Estonia and New Zealand wanted tax systems that are easier to administer.','de'=>'Estland und Neuseeland wollten Steuersysteme, die Bürger, Unternehmen und Finanzverwaltung mit weniger Einzelregeln bewältigen können.'],'implementation'=>['en'=>'Broad tax bases, fewer special rates and digital filing reduce separate calculations. Estonia taxes retained corporate profit differently, while New Zealand relies on a broad consumption tax.','de'=>'Breite Steuergrundlagen, wenige Sondertarife und digitale Erklärungen reduzieren getrennte Berechnungen. Estland besteuert Gewinne anders, solange sie im Unternehmen bleiben. Neuseeland erhebt eine breit angelegte Verbrauchsteuer mit wenigen Ausnahmen.'],'results'=>['en'=>'Compliance is simpler, but distributional questions remain. Consumption taxes can burden low incomes unless transfers compensate them.','de'=>'Die Steuererklärung und Kontrolle werden einfacher. Die Verteilungsfrage bleibt jedoch bestehen: Verbrauchsteuern belasten geringe Einkommen relativ stark, wenn Sozialleistungen oder andere Entlastungen das nicht ausgleichen.'],'transfer'=>['en'=>'Germany can pre-fill more data and reduce exceptions, but must show who pays more and who receives compensation.','de'=>'Deutschland kann mehr Angaben automatisch vorausfüllen und Ausnahmen abbauen. Jede Reform muss aber offenlegen, welche Gruppen mehr zahlen und wie besonders belastete Haushalte ausgeglichen werden.']],
    ['starting'=>['en'=>'Nordic countries and Switzerland needed trusted collection across different levels of government.','de'=>'Nordische Länder und die Schweiz mussten Steuereinnahmen zuverlässig zwischen nationaler, regionaler und kommunaler Ebene organisieren.'],'implementation'=>['en'=>'Clear administration and data exchange support different mixes of income, consumption, wealth and local taxes. Public services make the revenue side more understandable.','de'=>'Klare Zuständigkeiten und ein sicherer Datenaustausch erleichtern die Erhebung verschiedener Steuern. Für die Bevölkerung wird die Belastung eher nachvollziehbar, wenn zugleich sichtbar ist, welche öffentlichen Leistungen damit finanziert werden.'],'results'=>['en'=>'Collection is effective, but no common “Nordic tax model” exists. High trust was built over time and can fall when services disappoint.','de'=>'Die Steuererhebung funktioniert vergleichsweise zuverlässig. Ein einheitliches „nordisches Steuermodell“ gibt es jedoch nicht. Vertrauen entstand über Jahrzehnte und kann sinken, wenn staatliche Leistungen schlechter werden.'],'transfer'=>['en'=>'Germany needs transparent use of revenue and reliable services alongside simpler rules.','de'=>'Deutschland sollte nicht nur Steuerregeln vereinfachen, sondern auch verständlich zeigen, wofür Einnahmen verwendet werden und welche Leistungen Bürger dafür erhalten.']],
  ],
  'prerequisites'=>['en'=>['A complete financing plan and distribution table','Coordination with benefits, childcare and social insurance','Simple digital filing with human support and appeal rights'],'de'=>['Vollständiger Finanzierungsplan und Verteilungstabelle','Abstimmung mit Transfers, Betreuung und Sozialversicherung','Einfache digitale Erklärung mit menschlicher Hilfe und Widerspruchsrecht']],
 ],
 'health'=>[
  'problemDetail'=>[
   'en'=>['Germany spends much on health but does not always turn this into better coordination. Patients often move between family doctors, specialists, hospitals, rehabilitation and care without one team holding the full path. This creates repeated tests, waiting and avoidable admissions.','Ageing increases chronic illness and care needs while the workforce also ages. Reform therefore needs better use of staff, not only more money. Nurses, doctors, therapists, pharmacies and digital support must work as a team.'],
   'de'=>['Deutschland gibt viel für Gesundheit aus, erreicht damit aber nicht immer gute Koordination. Patienten wechseln zwischen Hausarzt, Facharzt, Krankenhaus, Reha und Pflege, ohne dass ein Team den gesamten Weg steuert. Das führt zu doppelten Untersuchungen, Wartezeit und vermeidbaren Einweisungen.','Die Alterung erhöht chronische Krankheiten und Pflegebedarf, während auch das Personal älter wird. Reformen brauchen deshalb einen besseren Einsatz der Fachkräfte und nicht nur mehr Geld. Pflege, Ärzte, Therapie, Apotheken und digitale Hilfe müssen als Team arbeiten.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany has broad insurance coverage and many providers. Weak points are the border between outpatient and hospital care, uneven quality information and slow digital exchange. Rural areas face access risks when small facilities close before alternatives exist.','Useful measures are avoidable hospital admissions, treatment results, waiting time, patient safety and access by region. Counting beds or doctor visits alone can reward activity without proving better health.'],
   'de'=>['Deutschland hat eine breite Versicherung und viele Anbieter. Schwächen liegen an der Grenze zwischen ambulanter und stationärer Versorgung, bei ungleichen Qualitätsinformationen und langsamem Datenaustausch. Ländliche Räume verlieren Zugang, wenn kleine Angebote vor den Alternativen schließen.','Sinnvolle Kennzahlen sind vermeidbare Klinikaufnahmen, Behandlungsergebnisse, Wartezeit, Patientensicherheit und regionaler Zugang. Betten oder Arztbesuche allein belohnen Aktivität, beweisen aber keine bessere Gesundheit.']
  ],
  'outlook'=>['en'=>'Without integrated care, staff shortages and contribution pressure will rise by 2036. With stronger primary care and planned hospital networks, complex treatment can improve while routine care stays close to home.','de'=>'Ohne integrierte Versorgung steigen bis 2036 Personalengpässe und Beitragsdruck. Mit starker Primärversorgung und geplanten Kliniknetzen kann komplexe Behandlung besser werden, während Grundversorgung wohnortnah bleibt.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Denmark and Sweden faced ageing, chronic disease and costly hospital structures.','de'=>'Dänemark und Schweden standen vor Alterung, chronischen Krankheiten und teuren Klinikstrukturen.'],'implementation'=>['en'=>'They strengthened primary and municipal care and concentrated some complex hospital services. Digital records and regional planning support the patient path.','de'=>'Sie stärkten Primärversorgung und kommunale Hilfe und bündelten einen Teil komplexer Klinikleistungen. Digitale Akten und regionale Planung unterstützen den Behandlungsweg.'],'results'=>['en'=>'Specialised treatment can become safer and avoidable hospital use can fall. Longer travel and local resistance are real costs.','de'=>'Spezialisierte Behandlung kann sicherer werden und vermeidbare Kliniknutzung sinken. Längere Wege und lokaler Widerstand sind reale Kosten.'],'transfer'=>['en'=>'Germany should build ambulance, primary and community alternatives before reducing hospital capacity.','de'=>'Deutschland sollte Rettung, Primärversorgung und kommunale Alternativen aufbauen, bevor Klinikangebote sinken.']],
    ['starting'=>['en'=>'The Netherlands and Switzerland wanted universal coverage with clearer purchasing responsibility.','de'=>'Die Niederlande und die Schweiz wollten eine Versicherung für alle mit klarer Verantwortung für Kosten und Behandlungsqualität verbinden.'],'implementation'=>['en'=>'Compulsory regulated insurance combines standard benefits with purchasing and quality rules. Risk adjustment is needed so insurers do not avoid sick people.','de'=>'Alle Menschen müssen versichert sein, Leistungen und Wettbewerb werden jedoch staatlich geregelt. Ein finanzieller Risikoausgleich sorgt dafür, dass Versicherer nicht vor allem junge und gesunde Menschen auswählen.'],'results'=>['en'=>'Access remains broad and buyers have stronger roles. Complexity, premiums and risk selection still require strict control.','de'=>'Der Zugang zur Versorgung bleibt breit. Versicherer können Leistungen gezielter vereinbaren und Qualität einfordern. Beiträge, komplizierte Regeln und die Auswahl günstiger Risiken müssen dennoch streng kontrolliert werden.'],'transfer'=>['en'=>'Germany can improve outcome-based purchasing without copying a whole insurance market.','de'=>'Deutschland kann Krankenkassen stärker danach bezahlen und steuern lassen, welche Behandlungsergebnisse erreicht werden. Dafür muss es nicht das gesamte niederländische oder schweizerische System übernehmen.']],
  ],
  'prerequisites'=>['en'=>['Primary and community capacity before hospital closures','Interoperable records with patient control and audit logs','Regional access standards and public quality results'],'de'=>['Primär- und kommunale Kapazität vor Klinikschließungen','Interoperable Akten mit Patientenkontrolle und Zugriffsprotokoll','Regionale Zugangsstandards und öffentliche Qualitätsergebnisse']],
 ],
 'pensions'=>[
  'problemDetail'=>[
   'en'=>['A pension system divides the cost of longer retirement between contributions, taxes, retirement age and benefit levels. No reform can remove this arithmetic. It can only make the choice clear, fair and gradual.','Funded pensions can spread risk across time and markets, but they add market and fee risk. Public pay-as-you-go insurance remains important because it shares wage, disability and longevity risks across society.'],
   'de'=>['Ein Rentensystem verteilt die Kosten eines längeren Ruhestands auf Beiträge, Steuern, Rentenalter und Leistungsniveau. Keine Reform kann diese Rechnung abschaffen. Sie kann die Entscheidung nur klar, fair und schrittweise machen.','Kapitalgedeckte Rente kann Risiken über Zeit und Märkte verteilen, bringt aber Markt- und Gebührenrisiken. Die gesetzliche Umlage bleibt wichtig, weil sie Lohn-, Erwerbsminderungs- und Langlebigkeitsrisiken gemeinsam trägt.']
  ],
  'germanyDetail'=>[
   'en'=>['The number of retirees rises faster than the number of contributors. Early retirement is used more often by healthier and higher-income workers, while people in hard jobs may not be able to work longer. This makes a single age rule socially uneven.','A complete reform needs minimum-income protection, disability routes, flexible work and better employment for older people. It should publish effects for generations, income groups and occupations.'],
   'de'=>['Die Zahl der Rentner wächst schneller als die der Beitragszahlenden. Früher Ausstieg wird häufiger von gesünderen Menschen mit höherem Einkommen genutzt, während Menschen in schweren Berufen oft nicht länger arbeiten können. Eine einzige Altersregel wirkt deshalb sozial ungleich.','Eine vollständige Reform braucht Schutz vor Armut, Wege bei Erwerbsminderung, flexible Arbeit und bessere Beschäftigung Älterer. Sie sollte Wirkungen nach Generation, Einkommen und Beruf offenlegen.']
  ],
   'outlook'=>['en'=>'Delaying adjustment makes the later change larger. By 2036, transparent automatic rules can reduce repeated political crises, but only if hardship protection is credible.','de'=>'Je länger eine Anpassung verschoben wird, desto stärker müssen später Beiträge, Steuern, Rentenalter oder Leistungen verändert werden. Klare Regeln können kurzfristige politische Eingriffe begrenzen. Sie sind aber nur akzeptabel, wenn Menschen mit niedrigen Einkommen oder körperlich belastenden Berufen verlässlich geschützt werden.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Sweden and Canada wanted pension finance that reacts to demographic and economic change.','de'=>'Schweden und Kanada wollten Rentenfinanzen, die auf demografischen und wirtschaftlichen Wandel reagieren.'],'implementation'=>['en'=>'Sweden uses automatic balancing in its public system. Canada combines public pensions with a professionally managed reserve fund at arm’s length from daily politics.','de'=>'Schweden nutzt automatischen Ausgleich im öffentlichen System. Kanada verbindet staatliche Rente mit einem professionell und politisch unabhängiger verwalteten Reservefonds.'],'results'=>['en'=>'Rules make financing more visible and reserves diversify risk. Automatic adjustment can lower expected benefits and needs a social floor.','de'=>'Regeln machen Finanzierung sichtbarer und Reserven verteilen Risiken. Automatische Anpassung kann erwartete Leistungen senken und braucht ein soziales Mindestniveau.'],'transfer'=>['en'=>'Germany can use transparent stabilisers and independent funds, but should protect hard careers and low lifetime earnings.','de'=>'Deutschland kann transparente Stabilisatoren und unabhängige Fonds nutzen, muss aber schwere Berufe und geringe Lebenseinkommen schützen.']],
    ['starting'=>['en'=>'Australia and the Netherlands wanted retirement income from more than the public pillar.','de'=>'Australien und die Niederlande wollten die Alterssicherung auf mehrere Quellen verteilen und die gesetzliche Rente durch betriebliche Vorsorge ergänzen.'],'implementation'=>['en'=>'Broad occupational saving creates funded assets with default contributions and professional management. Rules on fees, portability and risk differ.','de'=>'Für viele Beschäftigte fließen automatisch Beiträge in professionell verwaltete Vorsorgefonds. Wie hoch Beiträge und Gebühren sind und ob Ansprüche bei einem Arbeitgeberwechsel mitgenommen werden können, ist unterschiedlich geregelt.'],'results'=>['en'=>'Coverage and pension assets are high. Market losses, fees and gaps for interrupted careers remain important.','de'=>'Viele Beschäftigte sind erfasst und es wurde viel Vorsorgevermögen aufgebaut. Verluste an den Finanzmärkten, hohe Gebühren und Lücken durch Erwerbspausen bleiben jedoch wichtige Risiken.'],'transfer'=>['en'=>'Germany needs low fees, portable rights and credits for care or unemployment, not only a new savings product.','de'=>'Für Deutschland wäre nicht ein weiteres Sparprodukt entscheidend, sondern niedrige Gebühren, leicht übertragbare Ansprüche und ein Ausgleich für Zeiten der Pflege, Kinderbetreuung oder Arbeitslosigkeit.']],
  ],
   'prerequisites'=>['en'=>['Long transition with protected existing rights','Minimum pension and hardship routes','Low-fee independent management and clear public reporting'],'de'=>['Langer Übergang mit Schutz bereits erworbener Ansprüche','Mindestsicherung und besondere Regeln für soziale Härtefälle','Unabhängige Verwaltung mit niedrigen Gebühren und verständlichen öffentlichen Berichten']],
 ],
 'education'=>[
  'problemDetail'=>[
   'en'=>['Education reform takes time because better teaching reaches the labour market many years later. This delay makes stable policy more important. Frequent changes to structures can consume teacher time without improving learning.','The central issue is unequal opportunity. Children who start with language, poverty or family disadvantages often receive support too late. Digital devices help only when teachers, content and support are ready.'],
    'de'=>['Bildungsreformen wirken erst nach vielen Jahren: Kinder, die heute besser lernen, treten erst später in Ausbildung und Beruf ein. Deshalb braucht Bildungspolitik verlässliche Ziele. Ständige Änderungen von Schulformen und Zuständigkeiten binden Zeit, ohne automatisch den Unterricht zu verbessern.','Das zentrale Problem sind ungleiche Chancen. Kinder, die mit sprachlichen Schwierigkeiten, Armut oder geringer Unterstützung zu Hause starten, erhalten oft zu spät Hilfe. Tablets allein lösen das nicht. Entscheidend sind qualifizierte Lehrkräfte, gute Lerninhalte und erreichbare Unterstützung.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany has strong vocational training and many good schools, but learning results depend strongly on family background and region. Teacher shortages and administrative work reduce teaching time. Adult training is still difficult to combine with work and family.','Progress should follow basic skills, social gaps, attendance, teacher vacancies, successful vocational transitions and adult qualifications—not only spending or device numbers.'],
   'de'=>['Deutschland hat starke Berufsausbildung und viele gute Schulen, aber Lernergebnisse hängen stark von Familie und Region ab. Lehrkräftemangel und Verwaltung verringern Unterrichtszeit. Weiterbildung lässt sich noch schwer mit Arbeit und Familie verbinden.','Fortschritt sollte Grundkompetenzen, soziale Lücken, Anwesenheit, offene Lehrerstellen, erfolgreiche Berufsübergänge und Erwachsenenabschlüsse messen – nicht nur Ausgaben oder Geräte.']
  ],
   'outlook'=>['en'=>'By 2036, today’s pupils will enter a smaller workforce. Weak basic skills would deepen shortages and inequality; strong early support and adult learning would widen the usable talent pool.','de'=>'Bis 2036 treten die Schülerinnen und Schüler von heute in einen Arbeitsmarkt mit weniger verfügbaren Fachkräften ein. Fehlende Grundkenntnisse würden Personalmangel und soziale Ungleichheit verschärfen. Frühe Förderung und Weiterbildung im Erwachsenenalter erschließen dagegen Fähigkeiten, die heute ungenutzt bleiben.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Estonia and Finland aimed for high learning with smaller social gaps.','de'=>'Estland und Finnland wollten hohe Lernleistung mit kleineren sozialen Unterschieden.'],'implementation'=>['en'=>'Strong teacher education, coherent curricula, early support and school-level professional trust developed over many years. Estonia also built shared digital resources.','de'=>'Starke Lehrkräftebildung, klare Lehrpläne, frühe Förderung und professionelles Vertrauen entstanden über viele Jahre. Estland baute auch gemeinsame digitale Ressourcen auf.'],'results'=>['en'=>'Both performed above the OECD average in PISA 2022, though results and well-being challenges have changed over time.','de'=>'Beide lagen in PISA 2022 über dem OECD-Durchschnitt, auch wenn Ergebnisse und Belastungen sich über die Zeit verändert haben.'],'transfer'=>['en'=>'Germany can strengthen teacher preparation and early help. It cannot copy trust without reducing unnecessary control and giving schools support.','de'=>'Deutschland kann Lehrkräftebildung und frühe Hilfe stärken. Vertrauen lässt sich aber nur mit weniger unnötiger Kontrolle und guter Schulunterstützung aufbauen.']],
    ['starting'=>['en'=>'Switzerland and Singapore needed clear routes from school to skilled work.','de'=>'Die Schweiz und Singapur wollten jungen Menschen einen klaren Übergang von der Schule in qualifizierte Berufe ermöglichen.'],'implementation'=>['en'=>'Switzerland gives vocational education high status and close employer links. Singapore plans teacher development and STEM capacity very deliberately.','de'=>'In der Schweiz hat die berufliche Ausbildung einen hohen gesellschaftlichen Stellenwert und ist eng mit Betrieben verbunden. Singapur plant die Fortbildung von Lehrkräften und den Ausbau mathematisch-naturwissenschaftlicher Kompetenzen langfristig.'],'results'=>['en'=>'Transitions to skilled work are strong. Early selection and performance pressure can also reproduce inequality or harm well-being.','de'=>'Viele Jugendliche finden einen direkten Weg in qualifizierte Beschäftigung. Eine frühe Festlegung auf Bildungswege und hoher Leistungsdruck können jedoch soziale Unterschiede verstärken und die psychische Gesundheit belasten.'],'transfer'=>['en'=>'Germany should modernise dual training and guidance while keeping later routes open.','de'=>'Deutschland sollte die duale Ausbildung technisch und organisatorisch modernisieren und die Berufsberatung stärken. Ein späterer Wechsel zwischen beruflicher und akademischer Bildung muss weiterhin möglich sein.']],
  ],
  'prerequisites'=>['en'=>['Stable ten-year goals rather than constant structural reform','Protected teaching time and strong school support teams','Paid adult-learning time with recognised qualifications'],'de'=>['Stabile Zehnjahresziele statt dauernder Strukturreform','Geschützte Unterrichtszeit und starke Unterstützungsteams','Bezahlte Weiterbildungszeit mit anerkannten Abschlüssen']],
 ],
 'infrastructure'=>[
  'problemDetail'=>[
   'en'=>['Infrastructure fails slowly before it fails visibly. Deferred bridge, rail, school, grid and water maintenance creates larger repair bills and unreliable services. New projects receive more political attention than routine maintenance.','Money alone is not enough. Projects need prepared plans, skilled public clients, standard contracts, available land and firms that can deliver. A sudden spending programme can raise prices when this capacity is missing.'],
    'de'=>['Infrastruktur wird meist schrittweise schlechter, bevor Brücken, Bahnstrecken, Schulen, Stromnetze oder Wasserleitungen sichtbar ausfallen. Aufgeschobene Instandhaltung führt später zu höheren Kosten und häufigeren Störungen. Politisch attraktive Neubauten erhalten oft mehr Aufmerksamkeit als regelmäßige Wartung.','Mehr Geld allein löst das Problem nicht. Projekte brauchen genehmigungsfähige Pläne, qualifizierte Auftraggeber in der Verwaltung, geeignete Grundstücke und Unternehmen mit freien Kapazitäten. Fehlt das alles, kann ein großes Ausgabenprogramm vor allem Baupreise erhöhen, ohne schnell mehr Infrastruktur zu schaffen.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany has a backlog across transport, municipalities and digital networks. Planning is split across levels, while local authorities often cannot retain engineers or prepare applications. Maintenance data are not always comparable or public.','A useful pipeline ranks projects by safety, network value, climate resilience and readiness. Public milestones show whether delay comes from law, missing staff, changed design or procurement.'],
    'de'=>['Deutschland hat große Investitions- und Sanierungsrückstände bei Verkehr, kommunalen Einrichtungen und digitalen Netzen. Viele Kommunen können Fachingenieure weder gewinnen noch dauerhaft halten. Deshalb fehlen teilweise schon die fertigen Planungen, mit denen Fördermittel beantragt werden könnten. Vergleichbare öffentliche Zustandsdaten gibt es nicht überall.','Eine nachvollziehbare Prioritätenliste sollte Sicherheit, Nutzen für das gesamte Netz, Schutz vor Klimafolgen und Planungsstand berücksichtigen. Veröffentlichte Zwischenziele machen sichtbar, ob ein Projekt wegen rechtlicher Fragen, fehlenden Personals, geänderter Planung oder Problemen bei der Vergabe stockt.']
  ],
   'outlook'=>['en'=>'By 2036, climate stress and higher transport and energy demand will test old assets more strongly. A maintenance-first pipeline can improve daily reliability before every large new project is complete.','de'=>'Bis 2036 belasten Hitze, Starkregen sowie ein höherer Verkehrs- und Strombedarf die vorhandenen Anlagen zusätzlich. Wenn Sanierung und Wartung zuerst finanziert werden, kann die Zuverlässigkeit im Alltag schon steigen, bevor große Neubauprojekte abgeschlossen sind.'],
  'caseDetails'=>[
    ['starting'=>['en'=>'Switzerland and the Netherlands needed reliable networks in dense and geographically difficult areas.','de'=>'Die Schweiz und die Niederlande müssen Verkehrs- und Versorgungsnetze trotz dichter Besiedlung beziehungsweise schwieriger geografischer Bedingungen zuverlässig betreiben.'],'implementation'=>['en'=>'Long-term network plans, stable funds and coordination between transport, land and water create predictable project pipelines.','de'=>'Langfristige Netzpläne und verlässlich finanzierte Programme geben Behörden und Bauwirtschaft Planungssicherheit. Verkehrs-, Flächen- und Wasserplanung werden früh miteinander abgestimmt, damit sich Vorhaben nicht später gegenseitig blockieren.'],'results'=>['en'=>'Public transport and water protection are reliable by international comparison. Cost, local conflict and long planning still exist.','de'=>'Öffentlicher Verkehr und Wasserschutz funktionieren im internationalen Vergleich zuverlässig. Hohe Kosten, örtliche Konflikte und lange Planungszeiten verschwinden dadurch jedoch nicht.'],'transfer'=>['en'=>'Germany can protect multi-year maintenance budgets and link planning across modes and levels.','de'=>'Deutschland kann mehrjährige Budgets für Wartung und Sanierung vor kurzfristigen Kürzungen schützen. Außerdem sollten Bahn, Straße, Wasser und Flächennutzung über Verwaltungsgrenzen hinweg gemeinsam geplant werden.']],
    ['starting'=>['en'=>'Japan and Spain used sustained rail investment to change national mobility.','de'=>'Japan und Spanien bauten ihre Schienennetze über viele Jahre gezielt aus, um Reisezeiten zu verkürzen und Regionen besser zu verbinden.'],'implementation'=>['en'=>'Standard designs, strong delivery bodies and long programmes built large networks. Service planning was as important as construction.','de'=>'Wiederverwendbare technische Standards, spezialisierte Projektorganisationen und langfristige Ausbauprogramme ermöglichten große Netze. Ebenso wichtig wie der Bau war ein Fahrplan, der gute Anschlüsse und eine ausreichende Auslastung sicherstellt.'],'results'=>['en'=>'Travel times fell on successful corridors. Some low-demand routes and high maintenance costs show the risk of prestige investment.','de'=>'Auf stark genutzten Verbindungen sanken die Reisezeiten deutlich. Schwach ausgelastete Strecken und hohe Wartungskosten zeigen jedoch, dass politisch attraktive Prestigeprojekte dauerhaft teuer werden können.'],'transfer'=>['en'=>'Germany should select corridors by network benefit and demand, then publish cost and use after opening.','de'=>'Deutschland sollte neue Strecken nach erwarteter Nachfrage und ihrem Nutzen für das gesamte Netz auswählen. Nach der Eröffnung müssen tatsächliche Kosten, Fahrgastzahlen und Zuverlässigkeit veröffentlicht werden.']],
  ],
  'prerequisites'=>['en'=>['Protected maintenance budgets and an asset register','Skilled public project teams and standard procurement','Transparent ranking, milestones and post-opening evaluation'],'de'=>['Geschützte Instandhaltungsbudgets und Anlagenregister','Fachkundige öffentliche Projektteams und Standardvergabe','Transparente Rangfolge, Meilensteine und Prüfung nach Eröffnung']],
 ],
 'energy'=>[
  'problemDetail'=>[
   'en'=>['An energy system must deliver electricity and heat at every moment, including dark, cold and low-wind periods. Comparing only annual generation hides the need for grids, storage, flexible demand, reserve capacity and exchange with neighbouring countries.','The choices have different risks. Fossil fuels create climate damage, price shocks and dependence on exporters that may use energy politically. Renewables need networks, space, storage and flexibility, but domestic wind and solar do not require continuous fuel imports. Their equipment and raw-material supply chains still need diversification.'],
   'de'=>['Ein Energiesystem muss Strom und Wärme zu jeder Stunde liefern – auch an kalten, dunklen Tagen mit wenig Wind. Der Blick auf die Jahresproduktion allein reicht deshalb nicht. Benötigt werden außerdem leistungsfähige Netze, Speicher, steuerbarer Verbrauch, Reservekraftwerke und Stromhandel mit Nachbarländern.','Jede Möglichkeit hat andere Risiken. Fossile Energien verursachen Klimaschäden und machen Deutschland abhängig von Weltmarktpreisen und Exportstaaten, die Energie als politisches Druckmittel einsetzen können. Wind- und Solarenergie benötigen dagegen keine laufenden Brennstoffimporte. Sie brauchen jedoch Flächen, Netze, Speicher und flexiblen Verbrauch. Auch die Lieferketten für Anlagen und Rohstoffe müssen auf mehrere Herkunftsländer verteilt werden.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany has expanded renewables, but grid and permit delays remain. Industry needs predictable prices and reliable supply, while households experience network costs and the heat transition directly. European trade helps, but neighbours can face the same demand peaks.','Nuclear power should not receive a “best practice” label. Existing reactors can produce low-carbon electricity, but new projects must also count financing, long construction times, decommissioning, waste, accident protection and social acceptance. France’s Court of Accounts estimated a total construction cost of about EUR 23.7 billion for Flamanville 3 and reported a twelve-year delay.'],
   'de'=>['Deutschland hat Wind- und Solarenergie stark ausgebaut. Der Ausbau der Stromnetze und viele Genehmigungen kommen jedoch nicht schnell genug voran. Industrieunternehmen benötigen verlässliche Versorgung und planbare Preise; Haushalte spüren Netzentgelte und den Umbau der Wärmeversorgung unmittelbar. Stromhandel in Europa hilft beim Ausgleich, doch bei Kälte können mehrere Länder gleichzeitig einen hohen Bedarf haben.','Kernkraft sollte nicht als allgemeines Vorbild bezeichnet werden. Bestehende Reaktoren können Strom mit geringen CO₂-Emissionen erzeugen. Bei Neubauten müssen jedoch Finanzierung, lange Bauzeiten, Rückbau, radioaktiver Abfall, Unfallschutz und gesellschaftliche Akzeptanz vollständig berücksichtigt werden. Frankreichs Rechnungshof schätzte die gesamten Baukosten von Flamanville 3 auf rund 23,7 Milliarden Euro; das Projekt verzögerte sich um zwölf Jahre.']
  ],
  'outlook'=>['en'=>'By 2036, electricity demand may rise through transport, heating and industry. Coordinated renewable, grid, storage and efficiency investment can lower fossil exposure and political dependence. Fusion may become important later, but official prototype programmes do not expect demonstration plants before the 2040s. It should be funded as research, not counted as secure supply in the 2036 plan.','de'=>'Bis 2036 dürfte Deutschland mehr Strom benötigen, weil Verkehr, Gebäudeheizung und Teile der Industrie auf Strom umgestellt werden. Werden Wind- und Solarenergie, Netze, Speicher und Energiesparen gemeinsam vorangebracht, sinkt die Abhängigkeit von fossilen Brennstoffen und ihren Lieferstaaten. Kernfusion könnte langfristig wichtig werden. Die offiziellen Forschungsprogramme erwarten erste Demonstrationsanlagen jedoch nicht vor den 2040er-Jahren. Forschung ist deshalb sinnvoll, Fusionsstrom darf aber nicht als gesicherter Beitrag zur Versorgung im Jahr 2036 eingeplant werden.'],
  'caseDetails'=>[
   ['starting'=>['en'=>'Denmark has little hydropower of its own and chose to build a system around wind, efficient heat supply and strong links with neighbouring electricity markets.','de'=>'Dänemark verfügt nur über wenig eigene Wasserkraft. Das Land setzte deshalb vor allem auf Windenergie, gut ausgebaute Wärmenetze und starke Stromverbindungen zu seinen Nachbarn.'],'implementation'=>['en'=>'Long-term targets supported onshore and offshore wind. Interconnectors, combined heat and power, district heating and heat storage add flexibility when wind output changes.','de'=>'Langfristig geltende Ausbauziele gaben Investoren Sicherheit für Windanlagen an Land und auf See. Wenn wenig Wind weht, helfen Stromimporte, Kraft-Wärme-Kopplung und Wärmespeicher beim Ausgleich. Bei viel Wind kann Strom exportiert oder zur Wärmeerzeugung genutzt werden.'],'results'=>['en'=>'In the IEA’s 2023 review, wind supplied 54% of Danish electricity; wind, bioenergy and solar together supplied 81%. The grid remained reliable, but slow grid investment and permitting barriers were already limiting further progress.','de'=>'Nach dem IEA-Bericht von 2023 stammten 54 Prozent des dänischen Stroms aus Windenergie. Wind, Bioenergie und Solarenergie lieferten zusammen 81 Prozent. Die Versorgung blieb zuverlässig. Zu langsamer Netzausbau und schwierige Genehmigungen bremsten jedoch bereits den weiteren Ausbau.'],'transfer'=>['en'=>'Germany can transfer offshore co-operation, integrated heat and power planning, stronger interconnectors and flexible demand. It should not copy questionable biomass use or assume that Germany has Denmark’s smaller system.','de'=>'Deutschland kann die Zusammenarbeit beim Ausbau von Windparks auf See, die gemeinsame Planung von Strom und Wärme sowie den Ausbau grenzüberschreitender Stromleitungen übernehmen. Auch Stromverbrauch sollte stärker in Zeiten mit hohem Angebot verschoben werden. Die umstrittene Nutzung von Biomasse ist dagegen kein Vorbild. Außerdem ist das deutsche Energiesystem wesentlich größer.']],
   ['starting'=>['en'=>'Portugal remained dependent on imported fossil fuels but had strong wind, solar and hydropower resources and a goal of broad electrification.','de'=>'Portugal war lange stark von eingeführten fossilen Brennstoffen abhängig. Gleichzeitig verfügt das Land über gute Bedingungen für Wind-, Solar- und Wasserkraft und wollte Verkehr, Gebäude und Industrie stärker mit Strom versorgen.'],'implementation'=>['en'=>'Portugal expanded wind, solar and hydropower, closed coal generation and linked renewable growth with efficiency and electrification. Its next step is proactive grid investment, storage, flexible demand and stronger exchange with Spain.','de'=>'Portugal baute Wind-, Solar- und Wasserkraft aus und beendete die Stromerzeugung aus Kohle. Parallel wurden Energiesparen und die Umstellung auf Strom gefördert. Nun müssen Netze und Speicher möglichst vor den neuen Anlagen entstehen. Außerdem soll Stromverbrauch zeitlich besser gesteuert und mehr Strom mit Spanien ausgetauscht werden.'],'results'=>['en'=>'The IEA’s 2026 review describes Portugal as having one of the lowest-carbon electricity systems among IEA members and says this reduced import dependence. It also warns that grid capacity and flexibility are not keeping pace everywhere.','de'=>'Die IEA bezeichnete Portugals Stromversorgung 2026 als eine der emissionsärmsten unter ihren Mitgliedsländern. Dadurch sank die Abhängigkeit von Energieimporten. Zugleich warnte sie, dass Netze, Speicher und Möglichkeiten zur Steuerung des Verbrauchs nicht überall schnell genug ausgebaut werden.'],'transfer'=>['en'=>'Germany can copy anticipatory grid planning, transparent congestion data, renewable acceleration areas and flexibility markets. Portugal’s sunshine and hydropower cannot be copied, and affordability for low-income households must remain part of the policy.','de'=>'Deutschland kann Stromnetze früher planen und öffentlich zeigen, an welchen Stellen Leitungen überlastet sind. Es kann außerdem geeignete Gebiete für Wind- und Solarenergie vorab prüfen und Unternehmen dafür bezahlen, ihren Verbrauch bei Netzengpässen zu verschieben. Portugals hohe Sonneneinstrahlung und Wasserkraft lassen sich nicht übertragen. Bei allen Maßnahmen muss Energie für Haushalte mit geringem Einkommen bezahlbar bleiben.']],
  ],
  'prerequisites'=>['en'=>['One public adequacy plan for renewable generation, grids, storage, reserve capacity and demand','Technology comparisons using full lifetime and system costs, environmental effects and delivery time','Early public and municipal participation with fair local benefits and nature protection','Diversified European supply chains for equipment and critical materials','A separate fusion research budget with milestones, open evaluation and no assumed contribution before commercial readiness'],'de'=>['Ein öffentlich nachvollziehbarer Plan muss zeigen, wie Wind- und Solarenergie, Stromnetze, Speicher, Reservekraftwerke und steuerbarer Verbrauch zusammen zu jeder Zeit den Bedarf decken.','Techniken müssen nach allen Kosten über ihre gesamte Lebensdauer, den zusätzlichen Kosten für Netze und Speicher, ihren Umweltfolgen und der benötigten Bauzeit verglichen werden.','Bevölkerung und Kommunen müssen früh beteiligt werden. Natur- und Artenschutz sind verbindlich zu prüfen; betroffene Orte sollen einen fairen finanziellen Vorteil erhalten.','Anlagen und wichtige Rohstoffe sollten aus mehreren europäischen und internationalen Lieferquellen stammen, damit keine neue einseitige Abhängigkeit entsteht.','Für Kernfusion braucht es einen eigenen Forschungsetat mit überprüfbaren Zwischenzielen und unabhängiger Bewertung. Solange die Technik nicht kommerziell einsatzbereit ist, darf ihr kein Beitrag zur Stromversorgung zugerechnet werden.']],
 ],
 'migration'=>[
  'problemDetail'=>[
   'en'=>['Migration can reduce labour shortages, but admission is only the first step. Skills must be recognised, language learned, housing found and family life made possible. Slow administration can turn a qualified person into an underemployed worker.','Domestic labour potential remains important. Better childcare, health, training and work for older people should happen alongside immigration. Otherwise migration becomes an excuse not to remove barriers already faced by residents.'],
    'de'=>['Zuwanderung kann den Fachkräftemangel verringern, doch ein Visum allein reicht nicht. Ausländische Abschlüsse müssen zügig geprüft werden. Zugewanderte benötigen passende Sprachkurse, eine Wohnung und verlässliche Möglichkeiten für den Familiennachzug. Dauern diese Schritte zu lange, arbeiten gut qualifizierte Menschen häufig unter ihrem eigentlichen Ausbildungsniveau.','Gleichzeitig sollte Deutschland das vorhandene Arbeitskräftepotenzial besser nutzen: durch verlässliche Kinderbetreuung, Gesundheitsvorsorge, Weiterbildung und altersgerechte Arbeitsplätze. Zuwanderung darf nicht als Ersatz dafür dienen, Hindernisse für bereits hier lebende Menschen abzubauen.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany has expanded skilled routes, yet visa processing, recognition, language access and local housing remain uneven. Employers often need help to recruit and retain internationally. Discrimination and insecure work reduce long-term integration.','Success should be measured after several years: work matching qualification, income, language, permanent status, family stability and regional retention—not only the number of visas.'],
    'de'=>['Deutschland hat neue Zugangswege für Fachkräfte geschaffen. Bearbeitungszeiten für Visa, Anerkennungsverfahren, verfügbare Sprachkurse und der Wohnungsmarkt unterscheiden sich jedoch stark nach Ort und Beruf. Vor allem kleinere Arbeitgeber benötigen Unterstützung bei Anwerbung, Behördenkontakten und Integration. Diskriminierung sowie unsichere Beschäftigung erschweren es, Fachkräfte dauerhaft zu halten.','Ob die Politik erfolgreich ist, zeigt sich erst nach mehreren Jahren: Arbeiten Menschen entsprechend ihrer Qualifikation? Steigen Einkommen und Sprachkenntnisse? Erhalten Familien einen sicheren Aufenthaltsstatus und bleiben sie in der Region? Die Zahl erteilter Visa allein beantwortet diese Fragen nicht.']
  ],
  'outlook'=>['en'=>'By 2036, labour demand will remain high in care, education, construction, technology and public services. Countries that offer fast, fair and stable routes will compete more successfully for people.','de'=>'Bis 2036 bleibt der Bedarf in Pflege, Bildung, Bau, Technik und öffentlichem Dienst hoch. Länder mit schnellen, fairen und stabilen Wegen gewinnen im Wettbewerb um Menschen.'],
  'caseDetails'=>[
    ['starting'=>['en'=>'Canada and Australia needed skilled workers across large regions.','de'=>'Kanada und Australien wollten qualifizierte Zuwanderung gezielt an ihrem Fachkräftebedarf und an regionalen Engpässen ausrichten.'],'implementation'=>['en'=>'Points, employer routes and regional programmes make selection criteria visible. Permanent and temporary routes are combined.','de'=>'Ein öffentliches Punktesystem bewertet zum Beispiel Ausbildung, Berufserfahrung und Sprachkenntnisse. Daneben können Arbeitgeber für konkrete Stellen Fachkräfte anwerben. Regionale Programme erleichtern die Einreise, wenn sich Bewerber verpflichten, zunächst in einer besonders betroffenen Region zu arbeiten. Einige Programme führen direkt zu einem dauerhaften Aufenthaltsrecht, andere beginnen mit einem befristeten Status.'],'results'=>['en'=>'Skilled intake is large, but qualification mismatch, temporary-worker abuse and housing pressure continue.','de'=>'Beide Länder gewinnen auf diesem Weg viele Fachkräfte. Dennoch arbeiten Zugewanderte teilweise unterhalb ihrer Qualifikation. Bei befristeten Programmen besteht ein erhöhtes Risiko von Abhängigkeit und Ausbeutung. In attraktiven Regionen verschärft zusätzliche Nachfrage außerdem den Wohnungsmangel.'],'transfer'=>['en'=>'Germany can make criteria and service times clearer, but must connect intake to recognition and housing capacity.','de'=>'Deutschland kann Auswahlregeln, benötigte Nachweise und maximale Bearbeitungszeiten klar veröffentlichen. Neue Zugangswege müssen jedoch mit schneller Berufsanerkennung, wirksamem Arbeitsschutz und ausreichendem Wohnraum verbunden werden.']],
    ['starting'=>['en'=>'New Zealand and Denmark wanted recruitment linked more closely to labour demand and integration.','de'=>'Neuseeland und Dänemark wollten die Anwerbung ausländischer Fachkräfte enger mit offenen Stellen und den Voraussetzungen für eine dauerhafte Integration verbinden.'],'implementation'=>['en'=>'Occupation and employer routes are combined with language and integration requirements. Rules change when labour demand changes.','de'=>'Der Zugang hängt entweder von einem nachgefragten Beruf oder von einem konkreten Arbeitsplatzangebot ab. Hinzu kommen Anforderungen an Sprache und Integration. Die Liste gesuchter Berufe wird angepasst, wenn sich der Arbeitsmarkt verändert.'],'results'=>['en'=>'Targeting can respond quickly, but changing lists create uncertainty and strict family rules can reduce attraction.','de'=>'So kann die Politik relativ schnell auf neue Engpässe reagieren. Häufig wechselnde Berufslisten erschweren Bewerbern und Unternehmen jedoch die Planung. Strenge Regeln für Partner und Kinder machen ein Land für international umworbene Fachkräfte weniger attraktiv.'],'transfer'=>['en'=>'Germany needs stable core routes plus limited fast adjustments, not a constantly changing occupation list.','de'=>'Deutschland braucht dauerhaft verständliche Grundregeln. Engpassberufe können zusätzlich schnell berücksichtigt werden, ohne das gesamte System ständig zu ändern.'] ],
  ],
  'prerequisites'=>['en'=>['Binding service times for visas and recognition','Language learning connected to paid skilled work','Equal labour standards, housing plans and family stability'],'de'=>['Verbindliche Bearbeitungszeiten für Visa und Anerkennung','Sprachlernen verbunden mit bezahlter Facharbeit','Gleiche Arbeitsstandards, Wohnplanung und Familienstabilität']],
 ],
 'resilience'=>[
  'problemDetail'=>[
   'en'=>['Defence is not only a military task. Armed forces depend on civilian power, transport, health, food, water, communications and government. The same systems are also needed in floods, pandemics and major cyber incidents.','Modern infrastructure is often private and built for efficiency, not long interruption. Resilience therefore requires contracts, standards, reserves and exercises before a crisis. It should not mean secret planning without democratic control.'],
    'de'=>['Verteidigung ist nicht nur Aufgabe der Streitkräfte. Auch das Militär ist auf Strom, Verkehrswege, Krankenhäuser, Lebensmittel, Wasser, Kommunikation und eine handlungsfähige Verwaltung angewiesen. Dieselben Systeme müssen bei Hochwasser, Pandemien und schweren Cyberangriffen funktionieren.','Ein großer Teil der kritischen Infrastruktur wird von privaten Unternehmen betrieben und ist auf einen effizienten Normalbetrieb ausgerichtet, nicht auf lange Ausfälle. Deshalb müssen Staat und Betreiber schon vor einer Krise Mindeststandards, Notfallverträge, Reserven und gemeinsame Übungen vereinbaren. Solche Vorbereitungen brauchen klare Gesetze und parlamentarische Kontrolle.']
  ],
  'germanyDetail'=>[
   'en'=>['Germany is rebuilding civil protection after long periods of low investment. Responsibility is divided across federal, state, municipal, business and voluntary bodies. Plans exist, but people do not always know their role and joint exercises are uneven.','Progress should test continuity: can government communicate, hospitals operate, water flow, payments work and transport recover? Exercises must publish lessons without revealing dangerous operational detail.'],
    'de'=>['Deutschland baut den Zivilschutz nach langen Jahren geringer Investitionen wieder aus. Die Verantwortung verteilt sich auf Bund, Länder, Kommunen, Unternehmen und Hilfsorganisationen. Es gibt Notfallpläne, doch Zuständigkeiten sind nicht überall bekannt und gemeinsame Übungen finden regional sehr unterschiedlich statt.','Fortschritt zeigt sich nicht an der Zahl der Konzepte, sondern im Belastungstest: Kann der Staat die Bevölkerung erreichen? Können Krankenhäuser weiterarbeiten, Wasserwerke liefern, Zahlungen abgewickelt und Verkehrswege wieder geöffnet werden? Nach Übungen sollten festgestellte Schwächen veröffentlicht werden, ohne sicherheitskritische Einzelheiten preiszugeben.']
  ],
  'outlook'=>['en'=>'By 2036, climate, cyber and military risks may overlap. All-hazards preparation can reduce cost because the same warning, backup and local-support systems serve several crises.','de'=>'Bis 2036 können Klima-, Cyber- und militärische Risiken zusammenfallen. Gefahrenübergreifende Vorsorge spart Aufwand, weil Warnung, Ersatzsysteme und lokale Hilfe mehreren Krisen dienen.'],
  'caseDetails'=>[
    ['starting'=>['en'=>'Finland and Sweden kept or rebuilt whole-of-society defence after security conditions worsened.','de'=>'Finnland und Schweden hielten auch nach dem Kalten Krieg an Teilen ihrer umfassenden Landesverteidigung fest oder bauten sie nach der verschlechterten Sicherheitslage wieder aus.'],'implementation'=>['en'=>'Government, municipalities, firms, armed forces and voluntary groups receive roles. Continuity, reserves, shelters, public guidance and exercises are planned together.','de'=>'Ministerien, Kommunen, Unternehmen, Streitkräfte und Hilfsorganisationen erhalten konkrete Aufgaben für den Krisenfall. Notstrom, Vorräte, Schutzräume, Informationen für die Bevölkerung und gemeinsame Übungen werden als zusammenhängendes System geplant.'],'results'=>['en'=>'Responsibilities are better known and civil support is practiced. The system costs money and can burden individuals and firms.','de'=>'Zuständigkeiten sind im Ernstfall eher bekannt und die Zusammenarbeit wird regelmäßig geübt. Vorsorge verursacht jedoch laufende Kosten und kann Unternehmen sowie Privatpersonen zusätzliche Pflichten auferlegen.'],'transfer'=>['en'=>'Germany can set common continuity goals and exercise them across levels while keeping parliament, courts and privacy safeguards.','de'=>'Deutschland kann für wichtige Bereiche verbindlich festlegen, welche Leistungen auch in einer Krise weiterlaufen müssen, und dies gemeinsam mit Ländern und Kommunen testen. Parlamentarische Kontrolle, Rechtsschutz und Datenschutz müssen dabei vollständig erhalten bleiben.']],
    ['starting'=>['en'=>'Estonia and Switzerland needed resilience with limited size and decentralised structures.','de'=>'Estland muss als kleines, stark digitalisiertes Land besonders widerstandsfähig gegen Cyberangriffe sein. Die föderale Schweiz muss dagegen viele dezentrale Stellen in die Krisenvorsorge einbinden.'],'implementation'=>['en'=>'Estonia invests in cyber recovery and digital continuity. Switzerland combines federal, cantonal, reserve and civil-protection responsibilities.','de'=>'Estland investiert in gesicherte Datenkopien und erprobte Verfahren, mit denen digitale Staatsdienste nach einem Angriff wieder anlaufen. In der Schweiz teilen sich Bund, Kantone, militärische Reserve und Zivilschutz klar abgegrenzte Aufgaben.'],'results'=>['en'=>'Repeated practice builds capability, but national geography and political tradition shape each model.','de'=>'Regelmäßige Übungen verbessern die tatsächliche Reaktionsfähigkeit. Die Modelle hängen jedoch stark von Größe, geografischer Lage und politischer Tradition des jeweiligen Landes ab.'],'transfer'=>['en'=>'Germany should copy tested recovery, decentralised backups and clear roles, not foreign institutions word for word.','de'=>'Für Deutschland sind getestete Wiederanlaufpläne, räumlich getrennte Sicherungssysteme und eindeutige Zuständigkeiten übertragbar. Die Institutionen anderer Länder sollten dagegen nicht unverändert kopiert werden.']],
  ],
  'prerequisites'=>['en'=>['Public continuity standards for NATO’s seven baseline areas','Regular joint exercises with published lessons','Parliamentary oversight, legal limits and fair financing of private duties'],'de'=>['Öffentliche Kontinuitätsstandards für die sieben NATO-Basisbereiche','Regelmäßige gemeinsame Übungen mit veröffentlichten Lehren','Parlamentskontrolle, Rechtsgrenzen und faire Finanzierung privater Pflichten']],
 ],
];
