<?php
declare(strict_types=1);

// Generated by scripts/fetch_real_wages_analysis.py; do not edit manually.
if (isset($_SERVER['SCRIPT_FILENAME']) && realpath((string) $_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    header('X-Robots-Tag: noindex, nofollow, noarchive', true);
    http_response_code(404);
    exit;
}

return json_decode(<<<'JSON'
{
  "comparison": {
    "Australia": 72018.439,
    "Austria": 78301.337,
    "Belgium": 80008.652,
    "Canada": 67900.601,
    "Czechia": 43607.144,
    "Denmark": 78090.445,
    "Estonia": 41019.039,
    "Finland": 63053.422,
    "France": 60483.173,
    "Germany": 76284.517,
    "Greece": 32412.152,
    "Hungary": 39144.852,
    "Iceland": 100605.43,
    "Ireland": 70112.825,
    "Israel": 57425.877,
    "Italy": 53864.157,
    "Japan": 50182.646,
    "Latvia": 44708.836,
    "Lithuania": 58111.602,
    "Luxembourg": 98529.748,
    "Mexico": 24463.122,
    "Netherlands": 80136.33,
    "New Zealand": 60896.229,
    "Norway": 73461.545,
    "Poland": 49074.08,
    "Portugal": 44937.011,
    "Slovakia": 37831.713,
    "Slovenia": 63375.61,
    "South Korea": 61259.161,
    "Spain": 57778.662,
    "Sweden": 61443.422,
    "Switzerland": 92285.059,
    "United Kingdom": 66299.139,
    "United States": 86977.138
  },
  "germanySeries": [
    {
      "value": 88.8,
      "year": 2007
    },
    {
      "value": 89.1,
      "year": 2008
    },
    {
      "value": 88.9,
      "year": 2009
    },
    {
      "value": 90.2,
      "year": 2010
    },
    {
      "value": 91.2,
      "year": 2011
    },
    {
      "value": 91.9,
      "year": 2012
    },
    {
      "value": 91.7,
      "year": 2013
    },
    {
      "value": 93.2,
      "year": 2014
    },
    {
      "value": 95.3,
      "year": 2015
    },
    {
      "value": 97.0,
      "year": 2016
    },
    {
      "value": 98.0,
      "year": 2017
    },
    {
      "value": 99.3,
      "year": 2018
    },
    {
      "value": 100.5,
      "year": 2019
    },
    {
      "value": 99.2,
      "year": 2020
    },
    {
      "value": 99.2,
      "year": 2021
    },
    {
      "value": 95.1,
      "year": 2022
    },
    {
      "value": 95.3,
      "year": 2023
    },
    {
      "value": 98.1,
      "year": 2024
    },
    {
      "value": 100.0,
      "year": 2025
    }
  ],
  "meta": {
    "countryCount": 34,
    "dataset": "OECD.ELS.SAE:DSD_EARNINGS@AV_AN_WAGE(1.0)",
    "definition": "Average annual wage per full-time-equivalent dependent employee in the total economy",
    "minimumCountryCount": 33,
    "minimumPeakShare": 0.85,
    "peakCountryCount": 38,
    "priceBase": 2025,
    "referenceYear": 2025,
    "retrievedAt": "2026-07-23",
    "sourceName": "OECD Data Explorer – Average annual wages",
    "sourceUrl": "https://data-explorer.oecd.org/vis?bp=true&df%5Bag%5D=OECD.ELS.SAE&df%5Bds%5D=dsDisseminateFinalDMZ&df%5Bid%5D=DSD_EARNINGS%40AV_AN_WAGE&df%5Bvs%5D=1.0&dq=..USD_PPP..Q..&pd=1990%2C&to%5BTIME_PERIOD%5D=false",
    "title": "OECD average annual wages",
    "unit": "constant 2025 US dollars, PPP converted"
  },
  "trendMeta": {
    "dataset": "62361-0020",
    "definition": "Nominal wage index divided by the consumer price index; gross monthly earnings including bonuses",
    "methodBreakNote": "2007–2021 quarterly earnings survey; earnings survey from 2022. The 2021/2022 transition has limited methodological comparability.",
    "sourceName": "Destatis GENESIS – Tabelle 62361-0020",
    "sourceUpdatedAt": "2026-05-28",
    "sourceUrl": "https://genesis.destatis.de/datenbank/online/statistic/62361/table/62361-0020",
    "title": "Germany real wage index",
    "unit": "Real wage index (2025 = 100)"
  }
}
JSON
, true, 512, JSON_THROW_ON_ERROR);
