name: 🧪 RealityCheck – Manual Fetch (Test)

on:
  workflow_dispatch: {}    # Nur manuell startbar

jobs:
  manual_run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PYTHON_VERSION || '3.11' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # manuell benötigte Pakete für RealityCheck:
          pip install requests pandas tqdm python-dotenv openai
          echo "✅ Dependencies installed"

      - name: Run full RealityCheck pipeline
        run: |
          echo "===== RealityCheck Manual Fetch Start $(date -u) ====="
          python ./scripts/fetch_data.py
          echo "===== Manual Fetch End $(date -u) ====="

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: fetch_log_manual
          path: data/fetch_log.txt
          retention-days: 7

      - name: FTP Deploy /data to InfinityFree
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir:  data
          server-dir: ${{ secrets.FTP_DIR }}
          state-name: .ftp-deploy-sync-state-data.json
          log-level: verbose
          exclude: |
            **/.git*
            **/.github*
            **/__pycache__/
            **/*.py
            **/*.md
            **/*.yml
