name: 🧪 RealityCheck – Manual Fetch (Data)

on:
  workflow_dispatch: {}    # Nur manuell startbar

jobs:
  manual_run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PYTHON_VERSION || '3.11' }}

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas tqdm python-dotenv openai
          echo "✅ Dependencies installed"

      - name: 🚀 Run full RealityCheck pipeline
        run: |
          echo "===== RealityCheck Manual Fetch Start $(date -u) ====="
          python ./scripts/fetch_data.py
          echo "===== Manual Fetch End $(date -u) ====="

      - name: 💾 Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: fetch_log_manual
          path: data/fetch_log.txt
          retention-days: 7

      - name: 🌍 FTP Deploy /data to InfinityFree (Safe)
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: data/
          server-dir: ${{ secrets.FTP_DIR }}/data/
          state-name: .ftp-deploy-sync-state-data.json
          log-level: verbose
          dangerous-clean-slate: false       # 🚫 Kein Löschen!
          exclude: |
            **/.git*
            **/.github*
            **/__pycache__/
            **/*.py
            **/*.yml
            **/pending/**

      - name: 🪶 Commit and push updated data to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RealityCheck Bot"
          git config --global user.email "bot@realitycheck"
          git add data/
          git commit -m "📊 Manual data update ($(date -u))" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      # ✅ Neuer Schritt: aktuelles UTC-Datum speichern
      - name: 🕐 Get current UTC date
        id: date
        run: echo "date=$(date -u '+%a, %d %b %Y %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: 📧 Send notification email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "RealityCheck Manual Run – ${{ job.status }}"
          to: ${{ secrets.EMAIL_TO }}
          from: RealityCheck Bot <${{ secrets.SMTP_USERNAME }}>
          secure: true
          body: |
            🧭 The RealityCheck manual fetch finished with status: **${{ job.status }}**

            📅 Date: ${{ steps.date.outputs.date }}
            🔗 View the full log in GitHub Actions.

            Repository: https://github.com/${{ github.repository }}
          attachments: data/fetch_log.txt
